### ISSUE TITLE
Improve handling of missing front gate

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#100]
A site name currently requires a frontGate separator to be correctly recognized as in:

     LYNN VALLEY CARE CENTRE -- 1070 LYNN VALLEY RD NORTH VANCOUVER, BC

The frontGate is often not included because users don't know they need them. Having the geocoder handle the following input address:

     LYNN VALLEY CARE CENTRE 1070 LYNN VALLEY RD NORTH VANCOUVER, BC

would be much more user-friendly.

**Comment by mraross** [comment]
A lot of these words look like part of an occupant or site name in the wrong position in a single-line address. Could the parser be enhanced to detect them?

**Comment by mraross** [comment]
This could also be handled by treating unmatched words at the beginning of an address as a fullSiteDescriptor. That way, the geocoder doesn't have to look up any occupant names. For example:

   Berwick House 4680 Elk Lake Drive Victoria, BC => Berwick House -- 4680 Elk Lake Drive Victoria, BC

This can be accomplished by starting from the first word and adding consecutive words followed by frontGate until you get a good match

as in:

      Berwick House 4680 Elk Lake Drive Saanich, BC [score = 23]
      Berwick -- House 4680 Elk Lake Drive Saanich, BC [score = 57]
      Berwick House -- 4680 Elk Lake Drive Saanich, BC [score = 90]

For further details, see #14

**Comment by cmhodgson** [comment]
I hope this can be addressed by a combination of n-gram based matching, and improving the handling of unknown words or word chains, based on keywords such as those mentioned. We dont have a good way to parse long site names efficiently.

**Comment by cmhodgson** [comment]
Estimate is for testing and tweaking specific examples, assuming n-gram matching logic is already in place.

**Comment by mraross** [comment]
This should be handled by a deepMatch heuristic (see #14)

**Comment by mraross** [comment]
Another approach is to add grammar rules to the parser that ignore all words in the back-alley. The back-alley is any information between the street-address and locality. Street-address is an address up to the street (e.g., 200 Burnside Rd W)

     street-address back-alley localityName provinceCode

**Comment by mraross** [comment]
The _Sliding Front Gate_ is one way to make frontGate optional. 

1. Insert a frontGate after the first word. If the resulting address makes a good match, you're done.
2. Insert a frontGate after the next word and test for a good match.
3. Repeat step 2 until you're out of words or you find a good match.

as in:

      Berwick House 4680 Elk Lake Drive Saanich, BC [score = 23]
      Berwick -- House 4680 Elk Lake Drive Saanich, BC [score = 57]
      Berwick House -- 4680 Elk Lake Drive Saanich, BC [score = 90]

For further details, see #14

**Comment by cmhodgson** [comment]
Planning to try a few approaches:
1) make the front gate optional in the grammar - this may cause a parsing slowdown but I want to know how bad it is - making this change in the grammar will have the same effect as the sliding front-gate heuristic but will apply at all parsing iterations (for better or worse)
2) make the front gate optional in particular cases, eg. site-name, locality (no civic number or street) similar caveats as above
3) add an alternative fall back which only looks for the site-name, locality case - this would only be attempted after other matches fail, and would only work on this specific case

The grammar changes are quick to implement, and with a short test we can confirm how much of a performance impact they have. The 3rd option is the least flexible but will likely have the least performance impact.

**Comment by mraross** [comment]
Please proceed

**Comment by mraross** [comment]
The following address has an unknown multi-word unitDesignator:

     APARTMENT BUILDING  221 -- 4280 MONCTON ST, RICHMOND, BC

which should be matched and standardized to:

     UNIT 221 -- 4280 MONCTON ST, RICHMOND, BC

In 4.0, it matches to:

     UNIT 221 APARTMENT -- 4280 MONCTON ST, RICHMOND, BC

with low confidence (67)

In Geocoder 4.1 silver, it geocodes to

**Comment by mraross** [comment]
Here's a another example:

     WATERSIDE 144 5880 DOVER CRES, RICHMOND, BC

maybe there are two patterns to check when sliding the frontGate across the address:

     garbage unitNumber civicNumber
  
     garbage civicNumber

**Comment by mraross** [comment]
Here's an example of a unitNumberPrefix separated from its unitNumber:

     C 7 6901 W ISLAND HWY, BOWSER, BC

which should match to:

     Unit C7 -- 6901 W Island Hwy, Bowser, BC

In 4.0, it matches to:

     UNIT 7 -- 6901 Island Hwy W, Bowser, BC

with a low confidence (67)

In 4.1 silver, it matches to:

**Comment by mraross** [comment]
Garbage pickup at the front gate works great. Here's some examples to try:

     APARTMENT BUILDING 221 4280 MONCTON ST, RICHMOND, BC

     front gate garbage 221 4280 moncton st, back alley garbage richmond, bc

The example with type locations of garbage returns a single fault, not two but I think that's ok. At most, maybe a slightly higher penalty (e.g., 4 instead of 3) ?

**Comment by mraross** [comment]
All the examples above now work:

     LYNN VALLEY CARE CENTRE 1070 LYNN VALLEY RD NORTH VANCOUVER, BC
     Berwick House 4680 Elk Lake Drive Saanich, BC
     APARTMENT BUILDING  221 4280 MONCTON ST, RICHMOND, BC
     WATERSIDE 144 5880 DOVER CRES, RICHMOND, BC
     C 7 6901 ISLAND HWY W,  BOWSER, BC
     c/o mom and dad 1175 douglas st victoria bc
     front gate garbage 221 4280 moncton st, back alley garbage richmond, bc

**Comment by cmhodgson** [comment]
The way we ended up fixing this was by allowing for garbage at the front of the input. This doesn't match it to a site name, but we don't currently have many site names to match to anyway. The garbage is identify and a small penalty fault is added.

**Comment by mraross** [comment]
Will continue this work in a future release.
