### ISSUE TITLE
Add missing locality aliases identified in rejected address analysis

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#101]
This issue is as a result of the analysis of the HLTH low scores address file.

Some localities have aliases that are taken into account by the standardization process. For example, Victoria is an alias for Saanich. Aliases, when used, cause a 4 points deduction from the address score.

There are a number of addresses in the HLTH file that use locality names for which the geocoder does not have an alias. This results in a deduction of 35 points for a “locality not matched” fault.

Could the appropriate Geocoder data source be enriched with additional locality aliases?
The table below shows a number of localities provided in the HLTH file that are changed into a different locality by the geocoder, with a 35 points deduction. These could be considered for addition into a locality alias list.

NOTE: the analysis of the HLTH file is still ongoing and may uncover additional candidate localities.

|inputString|locality|is Adjacent?|Example inputString
|---|---|---|---|
Armstrong | Deep Creek|No
Burns Lake|Tatalrose|No|15351 TATALROSE RD, BURNS LAKE, BC
Burns Lake|Cheslatta|No|10571 Cheslatta Rd, BURNS LAKE, BC
Cache Creek|Loon Lake|No|1514 LOON LAKE RD, CACHE CREEK, BC
Castlegar|Pass Creek|No|1754 PASS CREEK RD, CASTLEGAR, BC
Castlegar|Shoreacres|No|2582 SHOREACRES RD, CASTLEGAR, BC
Castlegar|Thrums|No|1414 THRUMS RD, CASTLEGAR, BC
Kamloops|Savona|No|6481 SAVONA ACCESS RD, KAMLOOPS, BC
Lone Butte|Bridge Lake|No|8041 BRIDGE LAKE NORTH RD, LONE BUTTE, BC
Nelson|Procter|No|7380 HARROP PROCTER RD, NELSON, BC
North Van|North Vancouver|No|352 W 14th St, North Van, BC
Ok Falls|Okanagan Falls|No|569 Hody Dr, Ok Falls, BC
Poco|Port Coquitlam|No|2248 McAllister Ave, Poco, BC
Rosedale|Popkum|No|10381 POPKUM RD S, ROSEDALE, BC
Salmon Arm | White Lake|No
Sorrento | White Lake|No|2067 WHITE LAKE RD, SORRENTO, BC
Van|Vancouver|No|223 W 7th Ave, Vancouver, BC|
Victoria | Willis Point|No|7136 WILLIS POINT RD, VICTORIA, BC
West Van|West Vancouver|No|1745 Esquimalt Ave, West Van, BC
150 MILE HOUSE|Spokin Lake|Yes|3492 SPOKIN LAKE RD, 150 MILE HOUSE, BC
Armstrong|Spallumcheen|Yes|4137 SPALLUMCHEEN DR, ARMSTRONG, BC
Burns Lake | Francois Lake|Yes|20010 COLLEYMOUNT RD, BURNS LAKE, BC
Burns Lake|Palling|Yes|14187 Palling Rd E, BURNS LAKE, BC
Chetwynd|Lone Prairie|Yes|1117 LONE PRAIRIE RD, CHETWYND, BC
Coombs | Errington|Yes|2089 ERRINGTON RD, COOMBS, BC
Cranbrook | Wycliffe|Yes|2928 WYCLIFFE STORE RD, CRANBROOK, BC
Cranbrook|Mayook|Yes|4232 MAYOOK SETTLEMENT RD, CRANBROOK, BC
Darcy | Devine|Yes|
Enderby | Deep Creek|Yes|1104 DEEP CREEK RD, ENDERBY, BC
Fort St James|Pinchi Lake|Yes|10167 PINCHI LAKE RD, FORT ST JAMES, BC
Fruitvale | Columbia Gardens|Yes|
Gibsons|Langdale|Yes|1525 LANGDALE RD, GIBSONS, BC
Gibsons|Port Mellon|Yes|2270 PORT MELLON HWY, GIBSONS, BC
Golden|Blaeberry|Yes|1954 BLAEBERRY SCHOOL RD, GOLDEN, BC
Grinrod | Grandview Bench|Yes|136 GRANDVIEW BENCH RD, GRINDROD, BC
Hope|Laidlaw|Yes|58051 LAIDLAW RD, HOPE, BC
Heffley Creek|Heffley Lake|Yes|2388 HEFFLEY LAKE RD, HEFFLEY CREEK, BC
Lindell Beach | Columbia Valley|Yes|
Lone Butte|Quesnel|Yes|7330 WATCH LAKE RD, LONE BUTTE, BC
Roe Lake|Lone Butte|Yes|7428 ROE LAKE CRES, LONE BUTTE, BC
Madeira Park|Garden Bay|Yes|6120 GARDEN BAY RD, MADEIRA PARK, BC
Nelson | Harrop|Yes|6010 HARROP-PROCTER RD, NELSON, BC
Nelson|Blewett|Yes|4260 Blewett Rd, Nelson, BC
New Denver|Rosebery|Yes|116 ROSEBERY LOOP RD, NEW DENVER, BC
Quesnel|Kersley|Yes|5199 BAKER-KERSLEY RD, QUESNEL, BC
Quesnel|Bouchie Lake|Yes|2525 BOUCHIE LAKE RD, QUESNEL, BC
Sicamouse|Solsqua|Yes|2048 CAMBIE-SOLSQUA RD, SICAMOUS, BC
Sorrento|Notch Hill|Yes|1977 NOTCH HILL RD, SORRENTO, BC
Sook|Otter Point|Yes|4570 OTTER POINT PL, SOOKE, BC
Salmon Arm | Deep Creek|Yes|
Tappen | Eagle Bay|Yes|
Tappen | White Lake|Yes|
Trail | Columbia Gardens|Yes|
Winlaw|Passmore|Yes|3918 PASSMORE UPPER RD, WINLAW, BC
Winlaw|Appledale|Yes|6607 APPLEDALE LOWER RD, WINLAW, BC

**Comment by mraross** [comment]
Yes, these locality aliases could be added to the geocoder configuration using the geocoder admin application.

**Comment by mraross** [comment]
See how adding adjacent localities as aliases affects these localities.

**Comment by mraross** [comment]
@gleeming Please add all non-adjacent aliases to the 4.1 geocoder at Refractions. They are all at the beginning of the list.

**Comment by mraross** [comment]
Adjacency determined for all aliases using the following request:

https://ssl.refractions.net/ols/pub/geocoder/addresses.html?&maxResults=10&matchPrecision=locality&brief=true&addressString=aLocalityName

**Comment by cmhodgson** [comment]
All of the non-adjacent cases in the list above have been added to Refractions geocoder config on cassandra.

**Comment by mraross** [comment]
@cmhodgson To best support North Van and West Van locality aliases, add the following aliases to the admin config:

North Van => District of North Vancouver, West Vancouver, Vancouver, Delta
West Van => District of North Vancouver, Vancouver, Delta, Lions Bay, Georgia Strait, Bowen Island

I suggest we remove the locality alias Van => Vancouver. It is rarely used compared to West Van and North Van and requires twenty-six aliases to be effective.

**Comment by cmhodgson** [comment]
I have added:
North Van => West Vancouver, Vancouver (North Vancouver and District of North Vancouver already existed)
West Van => North Vancouver, District of North Vancouver, Lions Bay, Georgia Strait, Bowen Island

I'm not sure why you are suggesting including Delta? And I added the West Van -> North Vancouver (city of) even though you didn't include it, I guess they are not technically neighbors, but we treat the city and district of North Van equally, in general. I guess I can accept dropping the van => vancouver alias. Once these changes are confirmed I will restart the server to enable them for testing.

**Comment by mraross** [comment]
@cmhodgson Let's leave locality alias Van => Vancouver in there but not add in the twenty-six aliases of Vancouver. It turns out that Van is quite a common abbreviation for Vancouver.

**Comment by cmhodgson** [comment]
These changes are now applied and the server is restarting.

**Comment by gleeming** [comment]
For the record I ran the 10k Health Ideas sample against the build with new aliases.  Only one case changed score, for input address 1 2883 KENT AVE, N VAN, BC.  In this and the previous build the output response is the same: UNIT 1 -- 2883 Bentall Rd, Vancouver BC.

However this is a malformed address case since there is no Kent Ave in North Vancouver.  I think the intended address was UNIT 1 -- 2883 East Kent Ave N, Vancouver BC which is not obvious from the input.

**Comment by mraross** [comment]
You're right about the East Kent address Graeme. It requires suffix matching to match it correctly and we didn't get around to that in this release.

**Comment by BK01** [comment]
Confirmed in Geocoder 4.1-Gold (TEST) config
