### ISSUE TITLE
Add non-standard streetType abbreviations identified in rejected address analysis

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#102]
This issue is a result of the analysis of the low scores address file from HLTH.

A number of addresses in the HLTH file contain locality and street type abbreviations that are non-standard as per Canada Post. However they appear in the expected location in the address. Currently, the penalty for these abbreviations 33 points (Unrecognized  word fault). If the following abbreviations are added to geocoder configuration data, these penalties can be avoided and many scores will rise above 90.

Abbreviation | Expansion | Example
|----|---|---|
Bv|Boulevard|2351 Parkway Bv, Coquitlam, BC
Bu|Boulevard|3176 Plateau Bu, Coquitlam, BC
Clo|Close|895 Academy Clo, Victoria, BC
Cre|Crescent|4965 Vista View Cre, Nanaimo, BC
Dri|Drive|1000 Thermal Dri, Coquitlam,BC; 8400 Forest Grove Dri, Burnaby,BC
Ok|Oak|1301 Ok Ave, Quesnel, BC
Ro|Road|7701 Central Saanich Ro, Saanichton,BC
Roa|Road|3942 Columbia Valley Roa, Cultus Lake, BC
Wa|Way|774 Great Northern Wa, Vancouver,BC

**Comment by mraross** [comment]
As long as abbreviations are longer than a single character and don't conflict with existing abbreviations, they can be added to the geocoder configuration using the geocoder admin application.

**Comment by mraross** [comment]
Created a CSV of [safe abbreviations](https://github.com/bcgov/ols-geocoder/blob/gh-pages/config/bc/abbreviations.csv) that should be used in geocoder 4.1.

**Comment by cmhodgson** [comment]
This is done on the Refractions Cassandra config.

**Comment by BK01** [comment]
Confirmed in 4.1-Gold (TEST) configuration
