### ISSUE TITLE
Disambiguate locality level bianyms

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#103]
When you enter Mill Bay into an app that uses BC Geocoder autocompletion, your pick list will include two identical results back:

 ![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/e59789f5-1712-48f3-a7a2-124b76bf6916)

This is because there are two Mill Bays in the province, one just north of the Malahat, one just north of Nass Bay. This is very confusing because you have no way of distinguishing the two. We call such a locality name a [bianym](https://github.com/bcgov/ols-geocoder/blob/gh-pages/glossary.md#bianym). BC has locality name bianyms because there is no administration area geography that sits between locality and province for all localities (e.g., Regional District does not apply to First Nations governments).

ICBC first brought this to our attention.

**Comment by mraross** [comment]
One approach to disambiguate locality name bianyms is for the geocoder to return a street-level match instead of a locality-level match. In the above example, this would be:

   Hwy 1, Mill Bay, BC
   Hwy 113, Mill Bay, BC

To implement this approach, the geocoder could precompute the list of locality bianyms and their associated street-level addresses in Geocodable BC Maker and do a bianym lookup on a per request basis.

**Comment by mraross** [comment]
On a geocoder/addresses request that specifies a matchPrecision or matchPrecisionNot list that excludes street-level matches, the geocoder should still include street-level bianyms.

**Comment by cmhodgson** [comment]
We will identify the number of GNIS localities which have names that are duplicates of ITN names. The preferred approach is to return the ITN locality that the GNIS locality is within, with a locality.isAlias fault. This way the original ITN locality can be return unchanged.

**Comment by mraross** [comment]
This issue will be solved by issue #122

**Comment by mraross** [comment]
Verified in v4.1 gold in test
