### ISSUE TITLE
Improving handling of alphabetic unit numbers with letter suffixes

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#104]
This issue is based on analysis of the HLTH low scores Geocoder file.

A number of addresses submitted to the Geocoder include unit numbers where the unit is made of a letter+number combination. The supplied addresses (in the HLTH file) include a space between the letter and the number for the unit, as below:
B 2 518 BEATTY ST, VANCOUVER, BC
C 2 1845 WEST 10TH AVE, VANCOUVER, BC
P 100 1518 W 70TH AVE, VANCOUVER, BC
P 2 1855 NELSON ST, VANCOUVER, BC

These addresses get a 33 point deduction in score for "unrecognized". When removing the space, the units are as found in BC Assessment data and the score goes to 99.

Could the Geocoder recognize this pattern, remove the space, and use a lesser score deduction?

**Comment by mraross** [comment]
Verified in 4.1 silver

**Comment by BK01** [comment]
Validated in Geocoder 4.1 gold release
