### ISSUE TITLE
Add support for ignoring a care-of (c/o) name element embedded in an address

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#11]
Given the following address:
   c/o Mary Smith, 1000 Main St, Rosebug, BC

the geocoder should return:

     1000 Main St, Rosebug, BC

and a fault of:  CARE_OF.ignored:1

There are 9,907 MCFD addresses that contain c/o elements in their children in care list. 
Advanced Ed also raised this issue since student addresses sometimes include such data and it currently requires manual labour to edit it out.

**Comment by cmhodgson** [comment]
This could significantly slow down parsing of addresses including "c/o" (or just "co"?) as there would be no reliable separator between the end of the c/o name and the beginning of the address. This is essentially identical to the problems with occupants and sites, as we have no knowledge of what words to expect to be in the c/o sections, and basically any number of any words are allowable.

**Comment by mraross** [comment]
This should be handled by a deepMatch heuristic as described in:

https://github.com/bcgov/ols-geocoder/issues/14#issuecomment-717542982

**Comment by mraross** [comment]
@cmhodgson There are 2300 addresses in MCFD file that start with c/o. Maybe half of those would become good matches simply by removing the "c/o"  because they don't have a person's name, just a civic or postal address. For example:

C/O 7518 - 115A STREET  DELTA
C/O GENERAL DELIVERY  CASSIAR

**Comment by cmhodgson** [comment]
I have added c/o to the postal element handling.

**Comment by cmhodgson** [comment]
Note that the approach we have take does not work for the original example:
c/o Mary Smith, 1000 Main St, Rosebug, BC
but would work for:
c/o 1000 Main St, Rosebug, BC
and the back alley logic handles cases such as:
1000 Main St, c/o Mary Smith, Rosebug, BC

**Comment by mraross** [comment]
c/o PO BOX 201, Quesnel, BC

returns:

     West Fraser Timber Pk, Quesnel, BC

instead of:

     Quesnel, BC
doesn't return:

     Quesnel, BC

**Comment by mraross** [comment]
Verified in v4.1 gold
