### ISSUE TITLE
Geocoder nodes can only accept a single cassandra cluster contact point

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ols-geocoder#112]
The datastax client supports registering more than one cassandra cluster contact point.
The current implementation of the geocoder will only accept a single contact point.

To take advantage of the distributed, resilient nature of cassandra, the geocoder should have the ability to accept and register multiple cassandra cluster contact points.

**Comment by cmhodgson** [comment]
I've implemented this now in my local code. The OLS_CASSANDRA_CONTACT_POINT environment variable now takes a comma-separated list of contact point hostnames/addresses.

**Comment by cmhodgson** [comment]
Note that this change is in ols-util and so it also affects the (next release version of) the router (bonus!).

**Comment by alixcote** [comment]
Not using cassandra anymore. Closing.
