### ISSUE TITLE
For street names with a directional in the name body, add an alias of the non-directional part

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#113]

**Comment by gleeming** [comment]
For street names with a directional in the name body, e.g. North Park, add an alias of the non-directional part in the FME prep scripts.  Same for localities.

**Comment by gleeming** [comment]
I added street name aliases (e.g. dir=N, namebody=Park) for cases with a leading directional (e.g. namebody=North Park), but the geocoder doesn't act any differently with them in the data.  Simply trying "N Park" returns no results for North Park St, Victoria.  The input currently needs a minimum of the St to get the desired hit.  This issue can probably only be resolved through a parser or code change.

Locality aliases with directional words do not need mappings created as they already work (e.g. N Saanich, W Kelowna)

**Comment by gleeming** [comment]
I have updated the script so it now handles cases with a name body directional as the first or last word, creating an alias record with a directional prefix or suffix.  Only one variant will be created for the six ITN names with dual directional name bodies, like North Baezaeko West FSR.
For results at a match precision of street, there are now many new street locality centroid names available from these aliases.  And for civic number/site/block matches, the aliases appear to function well, e.g. 900 Park N St Victoria BC

**Comment by BK01** [comment]
Tested in 4.1-gold (DLV)

1. 900 Park N St Victoria BC => 900 North Park St, Victoria, BC. [Faults include STREET_NAME.isAlias, STREET_DIRECTION.notSuffix]
2. North Baezaeko West FSR => North Baezaeko West FSR, Nazko, BC
3. N Park St, Victoria, BC => N Park St, Victoria, BC (STREET level match)
