### ISSUE TITLE
Add support for multiple spellings errors in site, street, and locality name matching

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#114]
For example, Omineca => Omenica. This could be handled by N-gram matching (see #15)

**Comment by cmhodgson** [comment]
We are not going to go with the n-gram matching approach for now, so we can fix this by allowing more spelling errors in longer words, in the trie lookup

**Comment by cmhodgson** [comment]
This is implemented now.

**Comment by BK01** [comment]
Validated in Geocoder 4.1-Gold (DLV)

1. Vancuovre, BC => Vancouver, BC [LOCALITY.spelledWrong]
2. Vicotira, BC => Victoria, BC [LOCALITY.spelledWrong]
3. 976 Maeers st, Vicotira, BC => 976 Meares St, Victoria, BC [STREET_NAME.spelledWrong, LOCALITY.spelledWrong]
