### ISSUE TITLE
Prevent locality hopping

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#115]
Locality hopping happens when the geocoder parser looks to other localities, sometimes clear across the province, to match an input address. The match it finds is usually a very poor one and the search would have been better stopped in the original locality with the appropriate faults and score returned. It isn't locality hopping when the parser follows an alias to an adjacent or nearby locality because it frequently resolves to the correct address. Locality hopping is a common complaint of our major clients.

Here are some examples of locality hopping:

1. A civic number is not in any block of a street within a locality as in:

     500 helmcken rd, victoria, BC => 500 Helmcken St, Vancouver, BC instead of Helmcken Alley, Victoria, BC  
 
which aliases to Vancouver through the BCGNIS community of Victoria-Parkside.

     5000 helmcken rd, victoria, BC => Helmcken Alley, Victoria, BC 

which is the best match because there is no Helmcken Rd in Victoria, but there is in View Royal and Saanich, and sure enough:

     500 helmcken rd, view royal, BC => Helmcken Rd, View Royal, BC
     500 helmcken rd, Saanich, BC => Helmcken Rd, Saanich, BC    

2. A street is not found in a given locality as in:

     200 21st Ave, prince george, BC => 200 21st Ave N, Cranbrook, BC

3. A PO Box number gets misinterpreted as a numbered street name in a different locality:

     BOX 188 Kaleden => 188 St, Pitt Meadows, BC

This is a major issue for both MoH and MCDF.

**Comment by mraross** [comment]
If we generate locality aliases for all adjacent localities, the parser should only look in locality aliases when a civic number is not in any block of a street  or a street is not found in the entered locality. The parser should not look in unaliased localities to find a block or street. Locality spell correction should still be allowed.

**Comment by cmhodgson** [comment]
The lookup is actually done from street name, to block face, to locality, given that all those fields exist in the parse.

The first case is pretty awful input, there isn't even a 21st ave in prince george, if you put that query into google maps it return the Century 21 real estate office in prince george. Do we absolutely never want to fall back to another, un-aliased locality, if we have a valid/spell-corrected locality in the parse of the input? This kind of rule will be even harder to implement using n-gram matching as the locality could be matched from anywhere in the string, potentially very fuzzily.

The second case, for some reason is returning a locality.isAlias fault, not sure what it thinks is aliased to vancouver.... this is where the improved match fault output with a string value would help.

**Comment by mraross** [comment]
There are up to 27,793 rejected addresses that can be improved by preventing locality hopping. They won't all become good matches but at least, they will be more accurate matches as in the examples above.

**Comment by cmhodgson** [comment]
We can prevent the helmcken case by preventing the combination of a partial locality match and a locality alias - perhaps that is just a bridge too far.

**Comment by cmhodgson** [comment]
We will change the matching logic to not match to other localities when there is a valid locality identified in the input.

**Comment by cmhodgson** [comment]
I added a new fault called LOCALITY.partialMatchToAlias worth 30 points, to prevent matching one word of a multi-word locality alias. This was necessary to prevent the helmcken, victoria -> victoria-parkview match.

**Comment by BK01** [comment]
Test results in Geocoder 4.1-Gold (DLV) show improvement over Geocoder 4.0.2.

500 helmcken rd, victoria, BC => Helmcken Alley, Victoria, BC
