### ISSUE TITLE
Add support for electoral areas at the matchPrecision level of locality

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#12]
If you geocode:

    3450 Cobble Hill Rd, Cobble Hill, BC

the correct electoral area will be returned:

     CVRD Electoral Area C (Cobble Hill)

If you geocode:

 Cobble Hll,BC

you get no electoral area.

Electoral area is particularly important for non-civic occupants as they tend to be located in unincorporated areas.

This feature is needed by Ministry of Finance to determine the correct tax jurisdiction for such taxes as B&B tax and speculation tax.

**Comment by mraross** [comment]
https://geocoder.api.gov.bc.ca/addresses.html?minScore=50&echo=true&brief=true&autoComplete=true&addressString=3450+Cobble+Hill+Rd%2C+Cobble+Hill%2C+BC

**Comment by mraross** [comment]
If it makes sense, do the same for matchPrecision level of street.

**Comment by gleeming** [comment]
In the street prep FME script there is already EA overlay, assignment and filtering logic being applied to the street segments layer.  This could be extended to generate a new ELECTORAL_AREA_ID field in the street locality centroids and localities layers.

The geocoder application would have to be modified to read in these new input fields, and to output them for STREET and LOCALITY level match results.

**Comment by gleeming** [comment]
Streets in a locality can span multiple EAs, so I recommend just sticking to enhancing the locality level matches.

FME script has been updated to produce the new field in the localities table.  It will now need to be accommodated by the geocoder.

**Comment by mraross** [comment]
Agreed.  EA's at the matchPrecision  level of Street don't make sense.

**Comment by gleeming** [comment]
To clarify how EA's are assigned, each ITN locality point (either its centroid or BCGNIS-positioned location) is overlaid on the EA polygon set.  As a result munis usually won't have a corresponding EA since their ITN locality point will almost always fall in a gap in the EA polygon coverage.

**Comment by cmhodgson** [comment]
The Electoral areas of localities are now being read in and output.

**Comment by BK01** [comment]
Validated in Geocoder 4.1-Gold (DLV):

Cobble Hill, BC
=>
electoralArea: "CVRD Electoral Area C (Cobble Hill)",
