### ISSUE TITLE
Model all BCGNIS names that aren't DRA localities as sites instead of localities

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#122]
Currently, we treat BCGNIS names that aren't DRA localities as localities. This causes some issues:

1. Duplicate localities which confuses app users when they are using autocomplete. This was first identified by ICBC in their Driver Exam Centre app.
 
2. localityType is being populated from BCGNIS feature types which can cause confusion (e.g., BCGNIS has a feature type of locality).

3. Indian Reserves are admin areas located within a DRA locality, there are not a locality by themselves. This is a major issue for MCFD where they have addresses like House 490, Malachan Reserve,  Ditidaht, BC. 

To solve these issues, we propose to model all BCGNIS names that aren't DRA localities as sites in non-civic addresses as in:

     Malachan Reserve (Indian Reserve) -- Ditidaht, BC

which includes the BCGNIS name followed by the BCGNIS feature type in brackets, the frontGate delimiter, then the DRA locality that overlaps the BCGNIS feature.

We can assign both parcelPoint and accessPoint to this site. Note that both points must be within the allowed distances from a named, DRA road.

Now we can define House 490 as a unit within the complex, Malachan Reserve as follows:

     House 490, Malachan Reserve (Indian Reserve) -- Ditidaht, BC

If available, House 490 may be assigned it own parcelPoint or it can inherit parcel and access points from the Malachan Reserve site.

This solution also eliminates all duplicate localities that BCGNIS names caused (e.g., Mill Bay near Kincolith and near the Malahat). This will please ICBC and all users of autocomplete.

To make this scheme work, we need to enhance the parser to be able to recognize a non-civic address without a frontGate as in:

     House 490 Malachan Reserve Ditidaht, BC

We also need to change the data integration workflow to handle BCGNIS names as sites instead of localities. We may want to replace the BCGNIS "locality" feature type to avoid confusion with the geocoder's use of the term.

A DRA locality is a populated place that has a defined boundary in the Digital Road Atlas. DRA localities completely cover the province. A DRA locality is assigned to left and right muni fields on DRA road segments and to the **locality** field in reference addresses of the BC Address Geocoder. DRA localities are defined and managed by GeoBC.

**Comment by gleeming** [comment]
Here's the rough plan.

For the locality JSON file creation, change the logic so we only use BCGNIS name matches that fall within an ITN locality to provide a better point geometry.  Use the same feature subset for the next step.

For the site candidates
1) Create a new BCGNIS script that matches unpunctuated names and overlaid point locations of target FCODE features with ITN locality polygons.  We don't want the consistent records as they are the ones already part of the JSON locality file.  For everything else, create a non-civic address site candidate that includes a cleaned up feature code description, e.g. Quaniwsom 2 (Indian Reserve) -- BC
2) Ensure that the batch geocoding and scoring/reconciliation stages work for NCAPs that have no street (the DataBC NCAPs work fine but all are street cases).

**Comment by mraross** [comment]
Maybe only BCGNIS names that are bianyms in BCGNIS need to have their feature type in brackets included in their name. For example,

     Mill Bay -- Gingolith, BC

doesn't need its feature type because it is much different than:

     Mill Bay, BC

whereas

     Shuswap (locality) -- Anglemont, BC
     Shuswap (Indian Reserve) -- Anglemont, BC
     Shuswap (community) -- Anglemont, BC

all need feature type to differentiate themselves.

**Comment by mraross** [comment]
BCGNIS defines a locality as a named place or area, generally with a scattered population of 50 or less. I suggest we rename locality, sparsely populated place as in:

     Shuswap (sparsely populated place) -- Athalmer, BC

**Comment by mraross** [comment]
From: Jack, Carla FLNR:EX <Carla.Jack@gov.bc.ca> 
Sent: October 19, 2020 3:37 PM
To: Ross, Michael RA CITZ:EX <Michael.RA.Ross@gov.bc.ca>
Cc: Brammall, Johnathan CITZ:EX <Johnathan.Brammall@gov.bc.ca>; Leeming, Graeme CITZ:IN <gleeming@refractions.net>
Subject: RE: Improving support for BCGNIS populate place names that are not DRA localities.

Hi Mike,
Thanks for phoning and talking me through this plan. I think it makes sense and am supportive of your proposed approach.

I look forward to seeing how it looks. Don’t hesitate to be in touch again. 
Cheers,
Carla

**Comment by mraross** [comment]
This approach is superceded by _**BCGNIS name in DRA locality name**_ approach

**Comment by alixcote** [comment]
"This approach is superceded by BCGNIS name in DRA locality name approach". We believe this is now integrated into the new java data prep and no longer need this ticket.
