### ISSUE TITLE
Add all named bridges as sites

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#123]
Currently, named bridges appear in the streetNames of bridge road segments. This is very handy when you want to find a bridge by its name as in:

Johnson St Bridge

which is modelled as follows:

      streetName=Johnson
      streetType=St
      streetQualifier=Bridge

Modelling named bridges as streets becomes a problem when using autocomplete because it is now understood that autocomplete gives better results when the matchPrecisionNot=STREET is specified. This setting eliminates all streets from the top N results including all bridges.

By adding all bridges as non-civic addresses to the geocoder reference address list as in the following example:

     Johnson St Bridge -- Victoria,BC

 bridges become searchable  by name even when matchPrecisionNot=STREET.

**Comment by BK01** [comment]
Validated in Geocoder 4.1 gold release using Dec 2020 data and "Johnson St Bridge -- Victoria, BC"
