### ISSUE TITLE
Correct siteName not returned as top match when siteName.notMatched

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#125]
https://geocoder.api.gov.bc.ca/addresses.html?locationDescriptor=parcelPoint&echo=false&brief=false&maxResults=5&addressString=%09UNIT+170+Happy+House+--+22470+Dewdney+Trunk+Rd%2C+Maple+Ridge%2C+BC

**Comment by cmhodgson** [comment]
Seems that either the second match should have a siteName.partialMatch instead of a notmatched (because the unit is being included with the sitename) or the first match should have a unit.notMatched fault, either way the correct result would be returned. Likely a bug in the scoring logic.

**Comment by mraross** [comment]
Fixed in v4.1 silver. Verified in dev.

**Comment by BK01** [comment]
Validated in Geocoder 4.1 gold release
