### ISSUE TITLE
Make geocoder configuration management cloud-ready

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#127]
Replace Apache Cassandra with a file-based configuration manager.

1. Use GitHub to manage a set of configuration data files in CSV format. 

2. Write a configuration validation script that validates configuration data files and produces a validation report in Markdown format.

3. Update data integration process to include adding latest validated configuration data files to geocoder data store.

4. Ensure new cloud deployment process uses configuration data files.

Each configuration data file should contain data for a single configuration table. Here are the details:

### Configuration data files
|Filename|Schema
|----|----|
abbreviations.csv|abbreviation,mapsTo
globalDefaults.csv|name,value
localityAliases.csv|from,to,confidence
matchFaultValues.csv|fault,value
matchPrecisionValues.csv|precision,value
unitDesignators.csv|unitDesignator,description

The configuration files for the BC Address Geocoder are located in [github](https://github.com/bcgov/ols-geocoder/tree/gh-pages/config/bc)

The subdirectory /bc is used to inform developers that the configuration data files are only for use in British Columbia's BC Address Geocoder. Having them in the repo allows developers from other jurisdictions to see what production configuration files look like.

Currently, localityAliases.csv contains only sample data and will need to be replaced with real data. Since adjacent and BCGNIS related localityAliases will be autogenerated in v4.1, only non-adjacent aliases need to be managed in localityAliases.csv. The "to" column should contain localityName, not DRA locality id as is currently used.

The globalDefaults.csv file does not contain parcelKeys and parcelKeysRequired name-value pairs as these can't be visible to the public.

The matchPrecisionValues.csv file contains values for two proposed matchPrecisions: SITE_STREET and SITE_LOCALITY. This is to distinguish and reward site matches that are associated with addresses at different precision levels as follows:

matchPrecision|value|Example
|----|----|----
SITE|100|Robson Arms -- 1324 Robson St, Vancouver, BC
SITE_STREET|97|Centennial Candle -- Laurel Lane, Victoria, BC
SITE_LOCALITY|94|Mill Bay (locality) -- Gingolx, BC

SITE is considered  the highest (civic number) level of precision.

A parcelKeys file should be maintained on a secure server.

### Example ParcelKeys.csv file
|parcelKey|
|----|
key1
key2
key3

**Comment by alixcote** [comment]
Admin app is now hosted on openshift. Closing.
