### ISSUE TITLE
Handling of special symbols in street names

### ISSUE THREAD

**Issue by gleeming** [bcgov/ols-geocoder#129]
More and more first nations streets are being added to ITN that use characters outside the standard latin set.  We already gracefully deal with interchanging diacritics like À to A, ç to c, ë to e, Œ to OE, etc.  Then there are special symbols such as Pipeho:em Rd and ʔEqeʔat’in ʔEten.  The geocoder currently massages input strings to ignore certain characters (e,g, comma and dash) or convert to something else (e.g. colon and ampersand).  Examples and effects:

1) Colons are treated as a space for parsing and matching purposes, creating the effect of turning a one word name such as Pipeho:em Rd into a two word name Pipeho em Rd.  Simply typing Pipehoem Rd does not work in autocomplete, so perhaps colons need to be left intact, or perhaps the n-gram parser changes will simply make this a non-issue,

2) There are at least 3 ticks used in names: ` ' ’ that perhaps need to be treated interchangeably for input.  ITN isn't always consistent in usage as there is a Tl’etinqox Rd (forward tick) and also a Tl'etinqox ʔEten (standard tick).

3) I don't know if there is a mapping for ʔ that would make sense but currently in geocoder it is treated as its own unique character.  So trying to autocomplete and get out something like ʔEqeʔat’in ʔEten would be a challenge.

4) Forward slashes like in Clinton/Loon Lake FSR, Hutchison Lake, BC are removed for comparisons.  So this is the opposite of the colon case where here ClintonLoon Lake FSR, Hutchison Lake, BC works but Clinton Loon Lake FSR, Hutchison Lake, BC does not.  Apparently there are both slashed (128 segments) and dashed (1 segment) versions of that street name in Chasm.  I've reported the single inconsistent case to GeoBC and will look into other similar name cases (some may be valid on separate roads in disparate communities)

**Comment by mraross** [comment]
I don't think colons need to be removed.

**Comment by mraross** [comment]
I have asked the provincial toponomist for direction:

From: Ross, Michael RA CITZ:EX 
Sent: November 3, 2020 11:04 PM
To: Jack, Carla FLNR:EX <Carla.Jack@gov.bc.ca>
Cc: Kelsey, Brian CITZ:EX <Brian.Kelsey@gov.bc.ca>
Subject: How do we compare geonames with special characters in them?

Hi Carla,
How should we handle geoname comparisons with special characters beyond the western diacritics.  In a western diacritic like a cedilla under the "C" character, we just use a plain C instead. What should we do with special symbols in names like Pipeho:em Rd and ʔEqeʔat’in ʔEten    ? 

To be clear, we are going to return the correct official name but we need to normalize the geonames for comparison purposes.  Here's more details:

https://github.com/bcgov/ols-geocoder/issues/129

Any help would be greatly appreciated. I'm up for a chat if that's more convenient than an email response.

Cheers

Michael

**Comment by mraross** [comment]
Carla has provided clarification of special symbols in this email:

From: Jack, Carla FLNR:EX <Carla.Jack@gov.bc.ca> 
Sent: November 13, 2020 10:44 AM
To: Ross, Michael RA CITZ:EX <Michael.RA.Ross@gov.bc.ca>
Cc: Kelsey, Brian CITZ:EX <Brian.Kelsey@gov.bc.ca>
Subject: RE: How do we compare geonames with special characters in them?

Hi Michael,
As part of many geonames projects I will ask for “acceptable map labels” for names that use special characters that might be outside of the UTF-8 characters we can use in the BCGNIS. Even if we are able to support the special characters, I also often use the acceptable map label for internal-use-only in the ‘name key’ in the BCGNIS operational.  

Drawing from those acceptable map labels in relation to your question, I have seen the following as acceptable substitutions:
ʔ becomes ? (“ʔ” is a glottal stop, sometimes also symbolized by the number 7 in some orthographies)
o: becomes either ‘oo’ or ‘oh’ (“:” means the vowel is lengthened)
ŝ becomes s
etc.

Glad to hear that your output will be in the correct orthography. 

Just let me know if you want more information, clarification, to discuss further or anything else. 
Thank you,
Carla

**Comment by cmhodgson** [comment]
After further discussion we have decided:

1) Colons only follow "o" - any colons that follow an "o" will be removed from input and from the reference data for purposes of searching and matching - however the colon will be present in the returned match address if it is part of the reference data.

2) We can treat all ticks similarly to how apostrophe's are presently handled - if they are between letters, they will be removed and the neighboring letters connected - again, this is only for the purposes of matching and the reference data will be returned unmodified.

3) Presently, both the glottal stop character "ʔ" and "7" are used in the reference data interchangeably. Because "7" is considered both a digit and a valid representation of this character, we will map "ʔ" to 7. This may introduce some issues with other logic for handling combinations of numbers and letters such as ordinals ("7th") and affixes ("107A") - however this will not prevent correctly entered names from matching, it may cause some issues with spell correction.

4) We will replace slashes that are between two letters with spaces instead of simply deleting them (again, only for matching purposes). This will make them behave similarly to dashes - except in the case of fractions such as 1/2 which will remain as is.

**Comment by gleeming** [comment]
Following up on Carla's comments, I went looking for special characters in our current BCGNIS input file, which appears to be an older CSV text export format.  While it contains diacritic characters, it has remappings of all other special characters like glottal stops.

I downloaded a BCGNIS sample in GeoJSON and CSV from the DWDS gazetteer download tool, and both versions support special characters.  So a future task (and probably ticket since this one is geared towards street names) would be to look into modifying the FME site prep scripts to support the current BCGNIS export format.

**Comment by cmhodgson** [comment]
The special characters are now handled as I describe above. Note that this is not limited to street names, it applies to the entire input string.

**Comment by mraross** [comment]
If I enter this into demo app:

     ʔEqeʔat’in ʔEte

I get a best match of this:

     ʔEqeʔat’in ʔEten, Anahims Flat IR, BC

but if I enter this:

     ʔEqeʔat’in ʔEten

I get a best match of this:

     7 Ewen Ave, New Westminster, BC

**Comment by cmhodgson** [comment]
A new version with the fix for this is starting up right now.

**Comment by BK01** [comment]
Test results in Geocoder 4.1-Gold (DLV):

ʔEqeʔat’in%20ʔEte => ʔEqeʔat’in ʔEten, Anahims Flat IR, BC
ʔEqeʔat’in%20ʔEten => ʔEqeʔat’in ʔEten, Anahims Flat IR, BC
Tête Jaune Cache => Tête Jaune Cache in Tete Jaune, BC
Trépanier => Trépanier in Peachland, BC
'Kluémt 15 => 'Kluémt 15 near Campbell Island, BC
Tl'etinqox => Tl'etinqox ʔEten, Anahims Flat IR, BC
François Lake => François Lake, BC

**Comment by mraross** [comment]
Verified in v4.1 gold

**Comment by alixcote** [comment]
Verified and Closing.
