### ISSUE TITLE
Handle unitNumber stuck to unitDesignator 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#13]
For example,
unit201 => unit 201
ph2 => ph 2

This is needed by all clients to improve match robustness of geocoder and user experience

**Comment by cmhodgson** [comment]
I think at one time we force-separated all words with numbers and letters combined, at the boundary, so unit201 became unit 201  immediately. However I think that in order to support numbers with letter suffixes, eg. 10B, and also numbers with ordinal affixes eg. 7th, we removed separation. I think it should be safe to add this logic back, in the case where numbers and letters are combined and are not suffixes and are not ordinal affixes. We will also have to be careful about site and occupant names, eg. they will need to be separated in the same way at least in the search index, but would be shown in their original conjoined form in any results.

**Comment by mraross** [comment]
From Issue #81

The MSP address file has 981 addresses where the unit is a penthouse and the unit number format is PH (no space between PH and the remainder of the number).

These numbers are correct, and are as found in the BC Assessment address data which is known to the Geocoder.

The geocoder deducts 33 points from the score with an UNRECOGNIZED.notAllowed penalty.

Could the geocoder not deduct the penalty since the unit number is in fact correct?

Examples:
PHC 630 ROCHE POINT DR, NORTH VANCOUVER, BC
PH9 1163 THE HIGH ST, COQUITLAM, BC

**Comment by cmhodgson** [comment]
The example of phc is much harder to get, but we can now handle ph9, or unit201. This was handled by forcing a space between letters and numbers which have no space, at the tokenization stage.

**Comment by mraross** [comment]
Would this example be corrected:

   20 IR9 -- Dease Lake, BC

The correct interpretation is a bit more complicated that it appears:

  Unit 20 Dease Lake 9 -- Dease Lake, BC

**Comment by cmhodgson** [comment]
Assuming we know about the dease lake 9 site name, then yes I think it will find that match. it probably wont assume that the 10 is a unit but instead also find any sites with "20" in their name - again, unless we know about unit 20 at dease lake 9, which as of now we have no way to load that data.

**Comment by mraross** [comment]
But it does return the correct interpretation given the following:

20 IR 9 -- Dease Lake, BC

**Comment by mraross** [comment]
The following address contains a building id as a unit number prefix:

     C7 6901 W ISLAND HWY, BOWSER, BC

which now gets turned into:

The following address contains a building id as a unit number prefix:

     C7 6901 W ISLAND HWY, BOWSER, BC

because geocoder 4.1 silver treats the C in C7 as a unitDesignator and separates it from the 7 as follows:

The following address contains a building id as a unit number prefix:

     C 7 6901 W ISLAND HWY, BOWSER, BC

This, unfortunately is incorrect. The C and the 7 must stick together. Only known unitDesignators should be unstuck from their unit numbers.

**Comment by cmhodgson** [comment]
There is a new release this morning; the space is still there, but the C is not treated as a unit designator, it is a prefix part of the unit number. This is because of the new tokenization that separates letters and numbers.

**Comment by mraross** [comment]
Here is an address in our reference data that has a unit number prefix:

A114-20211 66 Ave, Township of Langley, BC

**Comment by mraross** [comment]
The following test cases now work:

     A114-20211 66 Ave, Township of Langley, BC
     unit201 1175 Douglas St, Victoria, BC
     PH9 1163 THE HIGH ST, COQUITLAM, BC
     C7 6901 ISLAND HWY W, BOWSER, BC
     

The following still don't work:

          PHC 630 ROCHE POINT DR, NORTH VANCOUVER, BC

This is beyond the capability of our parser right now.

**Comment by cmhodgson** [comment]
And by "don't work", you mean that: 
`PHC 630 ROCHE POINT DR, NORTH VANCOUVER, BC`
returns only a 96 point civic number match, not recognizing the PHC as "penthouse c" for a 99 point unit number match. Still pretty decent.

**Comment by mraross** [comment]
Good point. I have updated my previous comment appropriately.

**Comment by BK01** [comment]
The following tests were successfully repeated in Geocoder 4.1-Gold (DLV)

 unit201 1175 Douglas St, Victoria, BC
 PH9 1163 THE HIGH ST, COQUITLAM, BC
 20 IR9 -- Dease Lake, BC
 C7 6901 ISLAND HWY W, BOWSER, BC
 A114-20211 66 Ave, Township of Langley, BC
 A 114-20211 66 Ave, Township of Langley, BC

PHC 630 ROCHE POINT DR, NORTH VANCOUVER, BC [to a score of 96]
