### ISSUE TITLE
Zip up geocoder data files to shorten geocoder boot time

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-geocoder#132]
If the Geocoder continues to use the various input files as they are, we should consider combining them into a single zip file to reduce transfer time from the storage location to the starting up app. They compress to about 20% size (200GB vs. 1TB). We should test to confirm, but this should reduce the startup time somewhat and possibly simplify the management of the dataset. 

This will likely require some additional memory or temporary disk storage on the application servers (Kubernetes pods) which may be undesirable. Perhaps the transfer time will not be relevant (especially if the temporary storage for the pods is on the same physical array as the main storage location).

**Comment by mraross** [comment]
Maybe put all data files except config data file into a single zip file. Config data file may change more frequently than other data.

**Comment by alixcote** [comment]
Low priority, will close but will review overall startup times at a later time. With rolling restart and 2 minutes per pod, not a priority.
