### ISSUE TITLE
Handle variations of postal element names

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#137]
P O BOX  STN  => PO BOX STN 
POSTAL STN   => STN 
POSTAL STATION  => STN 
General Delivery => GD [2,832 appearances in MCFD]

Official postal element examples:

GD STN A, Vancouver, BC
PO BOX 321 GD STN A, Vancouver, BC
GD, Gibsons, BC

**Comment by cmhodgson** [comment]
After the various changes to support more postal elements, these are the regex patterns used to identify them:
```
// postal code eg: V9K 1X9
Pattern.compile("\\b[ABCEGHJ-NPRSTVXY][0-9][ABCEGHJ-NPRSTV-Z]\\s*[0-9][ABCEGHJ-NPRSTV-Z][0-9]\\b",Pattern.CASE_INSENSITIVE),

// Postal Box eg: PO BOX ##
Pattern.compile("\\b(P\\s*O\\s*)?BOX\\s*[0-9]+\\b(?!.*\\/FG)",Pattern.CASE_INSENSITIVE),

// Mailbag/Rural Routes/Mail Route/SS eg: MAILBAG ##, RR ## 
Pattern.compile("\\b(((MAIL)?BAG)|LCD|COMP|RR|MR|SS|RURAL\\s+ROUTE)\\s*[0-9]+\\b(?!.*\\/FG)", Pattern.CASE_INSENSITIVE),

// General Delivery Station eg: GD STN ABC
Pattern.compile("\\b(POSTAL\\s+)?STN\\s+[^\\s]+\\b(?!.*\\/FG)", Pattern.CASE_INSENSITIVE),

// General Delivery
Pattern.compile("\\b(GD|GENERAL\\s+DELIVERY)\\b", Pattern.CASE_INSENSITIVE)
```

Note that the sub-pattern:
```
(?!.*\\/FG)
```
is a negative look-ahead for "/FG" which is what the '--' front gate is replaced with, so the patterns with this at the end are only looking after the front-gate, if there is one.

**Comment by mraross** [comment]
Verified in v4.1 gold.
