### ISSUE TITLE
pids queries are not working when the api key is submitted through GET

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ols-geocoder#139]
### _pids should work regardless of whether the `apikey` is passed through the `GET` request or through the `header`_

# Steps
## Part 1 - this works as expected - passing the `apikey` in the Header succeeds
```bash
curl -H 'apikey: ############################## \
   https://geocoderdlv.api.gov.bc.ca/parcels/pids/d92103d1-9da5-45d5-ae55-035503f0fec4.json
```
### Expected
```json
{
  "siteID": "d92103d1-9da5-45d5-ae55-035503f0fec4",
  "pids": "009332090|009332197|009332227|009332243|009332294|009332332"
}
```
### Actual
```json
{
  "siteID": "d92103d1-9da5-45d5-ae55-035503f0fec4",
  "pids": "009332090|009332197|009332227|009332243|009332294|009332332"
}
```
## Part 2 - This does not work as expected - passing the `apikey` on the GET request does not succeed
```
curl https://geocoderdlv.api.gov.bc.ca/parcels/pids/d92103d1-9da5-45d5-ae55-035503f0fec4.json?apikey=##############################
```
### Expected
```
{
  "siteID": "d92103d1-9da5-45d5-ae55-035503f0fec4",
  "pids": "009332090|009332197|009332227|009332243|009332294|009332332"
}
```
### Actual
```html
<!DOCTYPE html>
<html>
<head></head>
<body>
Invalid parameter: Invalid or no API key found in request</body>
```

**Comment by cmhodgson** [comment]
My code doesn't look for API keys, I believe this is entirely handled by Kong.

**Comment by dkelsey** [comment]
Thanks Chris.  I'll follow up with that.

**Comment by dkelsey** [comment]
Question then: why do we need to add the apikey to the `parcelKeys` setting?

**Comment by cmhodgson** [comment]
Sorry, It was hidden in an interceptor:
https://github.com/bcgov/ols-geocoder/blob/master/ols-geocoder-web/src/main/java/ca/bc/gov/ols/geocoder/rest/ApiKeyInterceptor.java

It is pretty straightforward... can you make the request directly (avoiding kong) and see if the same thing happens? Perhaps Kong is stripping the apikey? I don't know why it isn't all being handled by Kong, then I wouldn't need the parcelKeys setting. I recall this being some kind of workaround for a Kong issue or something specific about what we were trying to do.

**Comment by mraross** [comment]
The apikey shouldn't work in a GET request to the pids resource because then the pids resource can be hacked and BC Assessment will not be pleased. The pids resource needs a special access control group to limit access to certain apikeys, not all. I guess kong doesn't support such groups or we didn't have the plugin that did but that's where we're at. Please don't enable apikeys in a GET request to the pids resource.

**Comment by alixcote** [comment]
Not going to add to GET request right now. Closing.
