### ISSUE TITLE
accessPoint of 7782 Watch Lake Rd, Watch Lake, BC is way off

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#140]
accessPoint shown in green marker, parcelPoint shown in blue

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/ab32a249-5bf6-4cde-af6f-59cb8735d91d)

**Comment by gleeming** [comment]
This looks to be influenced by RNF ranges.  There are only two actual even address points around that civic number -- 7782 and 7800.  The RNF has a range to the north from 7770 to 7942, which is significantly out of position relative to the real parcel locations.  As a result they are likely shifting the geocoder range much farther north than we would want.

If the changes proposed to applying anchor point data were to be handled as per #88, this case would probably be fixed.

![image](https://user-images.githubusercontent.com/21045965/97209743-f1320180-1779-11eb-8fd4-07e211d34858.png)

**Comment by cmhodgson** [comment]
I understand that this issue is fixed by the new data, so no code fix is required.

**Comment by BK01** [comment]
Validated in Geocoder 4.1 gold release using Dec 2020 data
