### ISSUE TITLE
Eliminate rarely used properties from site representation internally but preserve their illusion in all interfaces

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#141]
There are some site properties that have never been populated by address authorities and seldom used by client applications. These properties could be eliminated from the internal representation of a site, saving some space and making room for new  properties such as adminAreas.  These site properties need to stay in all resource requests and responses to maintain backward compatibility.

The following properties are candidates for elimination:

- siteStatus
- siteRetireDate
- positionalAccuracy
- accessPointPositionalAccuracy

All API resources should continue to accept and return these fields set to the following values:

siteStatus = active
siteRetireDate = 9999/12/31
positionalAccuracy=medium
accessPointPositionalAccuracy=medium

**Comment by cmhodgson** [comment]
This has effectively already been done, any site with the expected default/null values for the fields:
```
siteName =null
unitNumber = null
unitDesignator = null
status = active
retireDate = 9999/12/31
```
uses a different version of the site class that has all of those fields hard coded to those values. You can see the code that does it here:
https://github.com/bcgov/ols-geocoder/blob/dev/ols-geocoder-core/src/main/java/ca/bc/gov/ols/geocoder/data/SiteFactory.java

We could look at adding the site positional accuracy to this list. Access point positional accuracy is stored in the access point. I thought at one time we did actually have different values for the positional accuracy fields... but perhaps that has changed.

**Comment by mraross** [comment]
Done
