### ISSUE TITLE
Collect metrics after every major feature implementation using the DataBC metrics calculation script

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#142]
Until a new batch geocoder snapshot is deployed at DataBC, run the metrics.py script on batch geocoder results after every major feature implementation.  metrics.py computes metrics such as average address score, address counts by matchPrecision, address counts by score intervals of 10, address list match accuracy, and fault counts by fault type. metrics.py generates reports in markdown format and data files in csv format. All files from a given run should be zipped up and emailed to DataBC.

**Comment by gleeming** [comment]
A spreadsheet was made listing metrics from incremental runs of 10k random sample Health Ideas data as well as major releases against the full 13M addresses.

**Comment by mraross** [comment]
Here's a summary of Address List Match Accuracy:

|Code Version|Data Version|Comments
|---|---|---|
4.0.2|Aug 2020 data|Baseline
4.0.2|Added adjacent localities as aliases, ITN address ranges, split street names, changed BCGNIS localities that aren't DRA localities from localities to sites with DRA localites|

**Comment by mraross** [comment]
Done.

**Comment by BK01** [comment]
Continuing to track ALMA using the script below for each release. Will continue to track in a separate document.
