### ISSUE TITLE
Improve handling of garbage found in an address

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#144]
Improve handling of unexpected words found in the back alley of an address. The back alley is any text between street-address and localityName. Street-address is an address up to the street. Here are some examples:

|addressString|Street Address|Back-alley|Locality|Cleaned|Score
|---|---|---|---|---|---|
1175 Douglas St, CIBC, Victoria, BC|1175 Douglas St|CIBC|victoria| 1175 Douglas St, Victoria, BC|97
1175 Douglas St Street, Victoria, BC|1175 Douglas St|Street|victoria| 1175 Douglas St, Victoria, BC|97
1175 Douglas St c/o Big Wave Dave Victoria, BC|1175 Douglas St|c/o Big Wave Dave|victoria| 1175 Douglas St, Victoria, BC|96
1175 Douglas St, Douglas St, Victoria Victoria, BC|1175 Douglas St|Douglas St, Victoria|Victoria|1175 Douglas St, Victoria, BC|97

Add grammar rules to the parser that ignore all text in the back alley. These grammar rules should only be applied after a clean address match, including a possible unit, fails.

**Comment by cmhodgson** [comment]
This has been implemented. Note that all of the parsing based approaches apply at effectively the same time, so it is up to the scoring to choose the least-faulty match among all possible identified matches. The approach used does allow for a leading unit, such as:

**Comment by mraross** [comment]
Sounds very exciting. Can't wait to test it.

**Comment by mraross** [comment]
https://ssl.refractions.net/ols/pub/geocoder/addresses.html?&maxResults=10&brief=true&addressString=tappen

**Comment by mraross** [comment]
This issue was found in the HLTH low scores address file.
Many addresses contain names of buildings, care homes, hotels, etc. These are generally provided after the street name, and may contain multiple words. Two examples are provided below:
0111 2095 MARINE DR HOLLYBURN HOUSE , WEST VANCOUVER, BC
1 3031 WILLIAMS RD EDGEWATER PARK TOWN HOUSE, RICHMOND, BC
In the HLTH file, there were:

297 addresses including the word HOUSE (as above)
89 addresses including the word LODGE (as in 2251 CADBORO BAY RD OAK BAY LODGE, VICTORIA, BC)
150 addresses including the word MANOR
74 addresses including the word CARE (as in 1070 LYNN VALLEY RD LYNN VALLEY CARE CENTRE, NORTH VANCOUVER, BC)
The fault provided by the Geocoder is 35 points for LOCALITY.notMatched:.
Could the Geocoder recognize these word chains that contain certain key words and soften the penalty?

**Comment by mraross** [comment]
9695 PREST RD , postal stn CHILLIWACK, BC =>  postalelement.notAllowed and  locality.missing
9695 PREST RD , postal station CHILLIWACK, BC => postalelement.notAllowed

need to handle postal stn. Can we use an abbreviation such as stn=>station?

**Comment by mraross** [comment]
CONDO 801 8280 LANSDOWNE RD, RICHMOND, BC => BC (no match)

**Comment by mraross** [comment]
19 2100 Mount Boucherie Rd West Kelowna
 => UNIT 19 -- 2100 Boucherie Rd, West Kelowna, BC  in version 4.0
 => UNIT 19 -- 2100 Mount Baldy Rd, Bridesville, BC in version 4.1 with the following fault:
Unrecognized.notAllowed: "BOUCHERIE RD WEST KELOWNA"

https://ssl.refractions.net/ols/pub/geocoder/addresses.html?locationDescriptor=parcelPoint&echo=true&brief=true&addressString=19+2100+MOUNT+BOUCHERIE+RD%2C+WEST+KELOWNA%2C+BC

**Comment by cmhodgson** [comment]
> CONDO 801 8280 LANSDOWNE RD, RICHMOND, BC => BC (no match)
This is unrelated to the back alley problem. Should we add condo to the list of unit designators?

**Comment by cmhodgson** [comment]
> 19 2100 Mount Boucherie Rd West Kelowna
> => UNIT 19 -- 2100 Boucherie Rd, West Kelowna, BC in version 4.0
> => UNIT 19 -- 2100 Mount Baldy Rd, Bridesville, BC in version 4.1 with the following fault:
> Unrecognized.notAllowed: "BOUCHERIE RD WEST KELOWNA"
> The word "Mount" is the source of the trouble.

If anything, this is an argument for increasing the penalty of the unrecognized fault based on the number of words in it. The previous logic for unrecognizeds, of just throwing out each word in turn and re-parsing, is no longer used, and so this example is not handled. That approach typically doubled the execution time of matches.

**Comment by mraross** [comment]
addressString|fullAddress| is fullAddress best match?|comments
|---|---|---|
555 Burrard St apt 206, Vancouver, BC| APT 206 -- 555 Burrard St, Vancouver, BC| yes
555 Burrard St apt 206A, Vancouver, BC|555 Burrard St, Vancouver, BC|No|APT 206 -- 555 Burrard St, Vancouver, BC

**Comment by mraross** [comment]
I have a more general way of naming faults related to garbage
UnknownPrefix,UnknownInfix,UnknownSuffix

Location of garbage in address|Fault Name
|---|---|
At beginning|UnknownPrefix.notAllowed
Between street and localityName|UnknownInfix1.notAllowed
Between localityname and provinceCode|UnknownInfix2.notAllowed
At end|UnknownSuffix.notAllowed

We don't look for garbage the end of an address now but we might in the future (e.g., Vancouver, BC Canada). 
Also, when we add support for countryCode, we could look for garbage between subCountryCode and CountryCode and this fault would be called UnknownInfix3.notAllowed

**Comment by cmhodgson** [comment]
This doesn't seem any better than the current approach which is at least somewhat self-explanatory.

**Comment by mraross** [comment]
Point taken.

**Comment by mraross** [comment]
In the demo app,

     201 A 201 A A St, Abbotsford, BC

the geocoder returns two top-ranking matches:

                              201 A A St, Abbotsford, BC
        UNIT 201A -- 201 A A St, Abbotsford, BC

Both score a 96. The first one has a front-garbage fault. If we increase this fault's penalty from 2 to 3, the unit won't be swallowed up. Do we have to also increase the other garbage fault penalties too?

**Comment by cmhodgson** [comment]
All of the garbage fault penalties are separate. We can adjust them individually. I also wonder if suffix.notmatched should be a zero-point or be combined with a unitNumber.notMatched into a single penalty... but that might introduce other new problems.

**Comment by mraross** [comment]
As agreed this morning, we will eliminate the unitNumberSuffix.notMatched fault and penalize unknown unitNumbers by one point whether the unknown unit number has a suffix or not.  This will correct the ranking problem with the 201A example.

**Comment by cmhodgson** [comment]
See #156.

**Comment by mraross** [comment]
Verified in v4.1 gold using the following example:

    201 A 201 A A St, Abbotsford, BC
