### ISSUE TITLE
When score is tied, a civicNumber-level match may come before a unit-level match 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#145]
In an address with a known unit and garbage in the back alley as in the following:

     10 bushby st unit 1 blah victoria bc

 the civic number level match comes first and before the unit level match as in:

     10 bushby st victoria bc
     Unit 1 -- 10 bushby st  victoria bc

Here's the url to test this:

https://ssl.refractions.net/ols/pub/geocoder/addresses.html?&maxResults=10&brief=true&addressString=10+bushby+st+unit+1+blah+victoria+bc

**Comment by cmhodgson** [comment]
Done on Refractions Cassandra config.

**Comment by cmhodgson** [comment]
Actually we changed our mind on this one, instead of changing matchPrecision values we are just adding a score sorting fallback, on equal scores, more accurate matchPrecisions sort higher.

**Comment by BK01** [comment]
Validated in Geocoder 4.1-Gold (DLV)

10 bushby st unit 1 blah victoria bc
=> UNIT 1 -- 10 Bushby St, Victoria, BC
=> 10 Bushby St, Victoria, BC
