### ISSUE TITLE
Reduce unrecognized penalty from 5 to 3 to more minor faults

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#146]
Reduce penalty from 5 to 3.

From: Ross, Michael RA CITZ:EX 
Sent: November 5, 2020 5:59 PM
To: 'Chris Hodgson' <chodgson@refractions.net>
Subject: RE: Back Alley Garbage

Can you reduce it to 3?  The following example:

   5766 SACHEM ROAD RR#1,CHEHALIS RESERVE AGASSIZ

Returns this:

 ![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/0dee7e46-e361-4827-a6b7-9f3d5b0484b2)

It would be nice if the geocoder could tolerate this common combo of errors and its nice to have an additional  point for another minor error.

**Comment by cmhodgson** [comment]
Done on refractions Cassandra config.

**Comment by mraross** [comment]
Verified in v4.1 gold in test.
