### ISSUE TITLE
In data prep scripts, ignore any occupant of a non-civic address whose occupant name is a duplicate of a DRA locality name

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#148]
In data prep scripts, ignore any occupant of a non-civic address whose occupant name is a duplicate of a DRA locality name. Here's an example:

     Mill Bay -- Ferry Rd, Mill Bay, BC

which is an occupant, whose name is identical to that of a DRA locality name. To eliminate user confusion, such occupants should be ignored by the data prep process.

The example occupant actually represents the ferry terminal on Ferry Rd in Mill Bay and should be renamed by the data custodian as follows:

     Mill Bay Ferry Terminal -- Ferry Rd, Mill Bay, BC

There are other, similarly misnamed occupants in the GSR list of terminals and ports.

**Comment by gleeming** [comment]
An enhancement has been implemented to the site_prep FME scripts that compares any NCAP candidate site name with ITN locality names.  Cases with matches are rejected.  From the August test data, this has led to the removal of 133 GSR entries with names like Sooke and Mill Bay.  In the future if GSR expands these names to be more descriptive, e.g. by appending Ferry Terminal, then they will no longer match with an ITN locality and will be retained as valid candidates.

**Comment by mraross** [comment]
Verified in v4.1 Gold using Mill Bay, BC.
