### ISSUE TITLE
Populated place names that are not DRA localities are no longer included in geocoder results without a frontGate character

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#154]
This is by design. to eliminate user confusion when confronted with multiple matches that have the same locality name in them such as:

     Boston Bar, BC
     Boston Bar 8, BC
     Boston Bar 9, BC
     Boston Bar 10, BC
     Boston Bar 11, BC

 We classified all populated place names that aren't DRA localities as sites within a DRA locality as follows:

     Boston Bar 8 -- Boston Bar, BC
     Boston Bar 9 -- Boston Bar, BC
     Boston Bar 10 -- Boston Bar, BC
     Boston Bar 11 -- Boston Bar, BC

We also tried to eliminate the need for the frontGate delimiter on input but we failed, so now the only way to see such reclassified populated place names is to include the frontGate delimeter in your input. So developers now have to teach users about the frontGate. This could be done in a number of ways but perhaps the simplest way is to show some examples below the address input text box as follows:

      ______________________________________________
     |______________________________________________| (search)
      Examples: 
         1175 Douglas St Victoria BC
         201A 1175 Douglas St Victoria BC
         Victoria, BC
         Douglas St and Yates St Victoria BC
         Delta Port Terminal Entrance -- Roberts Bank Rd Delta BC 
         Delta Creek Bridge --  Terrace BC
         Boston Bar 8 -- Boston Bar BC
         Brentwood Bay -- Central Saanich BC
         Fairfield -- Victoria BC
         Hwy 1 and Exit 366

Developers may also explain that, in an autocompleting address text box, you don't need to enter a full name before tacking on a frontGate. For example, to look up Delta Port Terminal Entrance, you could just enter:

     Delta --

and the geocoder will include the desired name as one of the address choices as follows:

     North Delta -- Delta, BC
     Delta Creek Bridge -- Terrace, BC
     Delta Port Entrance -- Roberts Bank Rd, Delta, BC
     Delta Port Exit -- Roberts Bank Rd, Delta, BC
     Delta Heritage Air Park -- Delta, BC

**Comment by mraross** [comment]
This approach has been superceded by using in or near instead of frontGate. See issue

**Comment by BK01** [comment]
Closing - superceded by using in or near instead of frontGate.
