### ISSUE TITLE
Add a fault for auto-completed address components

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-geocoder#155]
There is currently no fault corresponding to the automatic word extension (akin to infinite-length spell correction) done to the last word in autocomplete input. This means that in cases like
`Boston Bar`
The "Bar" can be extended to "Barret" or "Barkerville" and there is no cost to that, making it harder to match the exact locality of Boston Bar.
I think a smallish fault of 4-5 points is appropriate and will not break successful autocompletion.

**Comment by cmhodgson** [comment]
New Fault is called ADDRESS.autoCompleted and I've default it to 5 points. It seems to have little effect outside of where it does exactly what is needed, eg. the boston bar case above.

**Comment by mraross** [comment]
Verified in v4.1 gold using Boston Bar.
