### ISSUE TITLE
Combine UNIT_NUMBER and UNIT_NUMBER_SUFFIX notMatched Faults

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-geocoder#156]
The input:
> 201 A 201 A A St, Abbotsford, BC
returns two top-ranking matches:

>  201 A A St, Abbotsford, BC
>   UNIT 201A -- 201 A A St, Abbotsford, BC

Both score a 96, the first one gets two 1-point penalties for unitNumber and unitNumberSuffix not matching, while the second one gets 2-point penalty for front-door garbage. The unit number and suffix should be combined into one matching field, with a 1-point penalty for either or both values not matching.

**Comment by cmhodgson** [comment]
This seems to work well and has the desired affect, without breaking any of the ATP test cases.

**Comment by mraross** [comment]
Verified in dev using:

     201 A 201 A A St, Abbotsford, BC

**Comment by BK01** [comment]
Test results in Geocoder 4.1-Gold (DLV):

201 A 201 A A St, Abbotsford, BC
=>
UNIT 201A -- 201A A St, Abbotsford, BC

value: "",
element: "UNIT_DESIGNATOR",
fault: "missing",
penalty: 0
},
{
value: "201A",
element: "UNIT_NUMBER",
fault: "notMatched",
penalty: 1
},
{
value: "A",
element: "CIVIC_NUMBER_SUFFIX",
fault: "notMatched",
penalty: 1
