### ISSUE TITLE
Eliminate need for frontGate in subLocality addresses

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#161]
A subLocality address is a non-civic address of the form:

     [siteName] subLocalityName -- localityName provinceCode

A subLocalityName is an official populated place name (e.g., from BCGNIS) that is not an ITN locality but is contained in one. For example, Brentwood Bay is a village within the Municipality of Central Saanich and is represented in the geocoder as follows:

     Brentwood Bay -- Central Saanich, BC

Site-localities can have subsites. This is useful in site-localities where  all sites are uniquely numbered as in the following example:

     House 490, Boston Bar 1 -- Boston Bar, BC

## Implementation Ideas

Put all bcgnis populated places that aren't DRA localities into a parser class called subLocality. Use this class in rules to identify subLocalities without the need for a frontGate delimiter. Here's an example rule:

      subLocalityName [provinceCode]  => subLocalityName frontGate localityName, provinceCode 

which enables these transformations:

      Brentwood Bay, BC => Brentwood Bay -- Central Saanich, BC
      Boston Bar 1, BC  => Boston Bar 1 -- Boston Bar, BC

Here another example rule:

     siteName subLocalityName [provinceCode] => siteName, subLocalityName frontGate localityName, provinceCode

which enables this transformation:

     House 490, Boston Bar 1, BC  =>  House 490, Boston Bar 1 -- Boston Bar, BC

Yet another rule:

     postalElement subLocalityName [provinceCode] => subLocalityName frontGate localityName, provinceCode

which enables these transformations:

     PO BOX 2944 Brentwood Bay, BC => Brentwood Bay -- Central Saanich, BC
     GD Brentwood, Bay BC => Brentwood Bay -- Central Saanich, BC

**Comment by cmhodgson** [comment]
>  [siteName] subLocalityName -- localityName provinceCode

This is not how this is currently implemented; I think this ticket was written before we changed to use the "in" and "near" syntax. As it is now, Brentwood Bay shows up as:

> Brentwood Bay in Central Saanich, BC

Given that, I'm not sure how much of the rest of this issue is relevant.

**Comment by alixcote** [comment]
Thanks @cmhodgson We will close this ticket.
