### ISSUE TITLE
Address with abbreviated locality Poco works correctly in Online Geooder but not batch geocoder

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#169]
In geocoder 4.1 Silver in delivery, the following address:

     2248 McAllister Ave, Poco, BC

matches correctly to:

     2248 McAllister Ave, Port Coquitlam, BC

in Online Geocoder but not batch geooder.

**Comment by gleeming** [comment]
It works correctly in the Refractions CPF, so it isn't an issue with batching, more likely a deployment problem in delivery.

**Comment by BK01** [comment]
Resolved. Issue was related to the name of the maven module id (SNAPSHOT vs. RC).

**Comment by mraross** [comment]
Verified in Test
