### ISSUE TITLE
Geocode Results with the same score but fewer 0-penalty faults should come first

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-geocoder#17]
This issue is highlighted by the fact that these two addresses do not get de-duplicated in the address prep process:

1. 7931 Hwy 97 N, Kelowna, BC
2. CAMS RACE TRACK GAS -- 7931 Hwy 97 N, Kelowna, BC

The problem is that the 0-point penalty for STREET_DIRECTION.notMatchedInHighway means that there is no way to prefer an exact match of "Hwy 97 N" over the slightly incorrect "Hwy 97" with the 0-point fault. This duplicate address bug happens in the address prep phase, but this same problem is also evident at the user level, as the order of such matches is not consistent.

A possible way to fix this is to internally add a .01 point penalty for any 0-point fault. All external views would still see the integer value of the score, but the internal sorting mechanism would then be sure to put the better matches first.

bug fix requested by DataBC to improve user experience

**Comment by alixcote** [comment]
Penalty not happening anymore. Closing.
