### ISSUE TITLE
Take out all postal element handling from the regular expression stage of geocoder except postal code and c/o

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#174]
Given that the geocoder is supposed to just ignore all postal elements, the new garbage pickup logic in the lexical analyser and parser should be able to handle all postal elements without modification. 

Postal code needs to be handled in the regex because it normally appears after provinceCode.

Care-Of (c/o) needs to be handled in the regex so it doesn't get mangled by the slasher (e.g., c/o =\> c o)

By treating all postal elements as garbage, this will enable the geocoder to come up with clean locality matches for what are basically postal service addresses, and badly-forms one at that. Such matches are useful to clients that need to put an address into the correct administrative area, (e.g., MoH needs to put clients and client activities into the correct Community Health Service Areas)

**Comment by mraross** [comment]
Not a good idea after all. After studying the geocoding of postal service addresses, we found postal element words are being misinterpreted as street names and such words may be found after the provinceCode which spoils many a postal address match. So, the best approach is to eliminate c/o in a regex but move the handling of all other postal elements down into the lexical analyser and the parser.

**Comment by alixcote** [comment]
Closing. Added example to data to be included in machine learning.
