### ISSUE TITLE
Addresses with locality of  WEST WOLD  geocoding to FALKLAND

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#176]
When the input address has WEST WOLD (with a space) rather than WESTWOLD for the locality, Geocoder 4.1 geocodes to Falkland, and the lat/lon are slightly different than the lat/lon of the address without the space. WESTWOLD is the locality name.

Note: the score is above 90 in these examples, but it's being reported here because the lat/lon is different.

Examples:
Address: 4316 KAMLOOPS VERNON HWY, WEST WOLD, BC
4.1.: 4316 Hwy 97, Falkland, BC
Score: 92, Precision: 99
Faults:
"HWY WEST WOLD" PROVINCE_GARBAGE.notAllowed 2
"KAMLOOPS" STREET_NAME.partialMatch 1
"VERNON" LOCALITY.isAlias 4
"KAMLOOPS" STREET_NAME.isHighwayAlias 0

Address: 4748 KAMLOOPS VERNON HWY, WEST WOLD, BC
4.1: 4748 Hwy 97, Falkland, BC
Score: 92 Precision: 99
Faults:
"HWY WEST WOLD" PROVINCE_GARBAGE.notAllowed 2
"KAMLOOPS" STREET_NAME.partialMatch 1
"VERNON" LOCALITY.isAlias 4
"KAMLOOPS" STREET_NAME.isHighwayAlias 0

**Comment by mraross** [comment]
I bet the location is different because there is a block in both Falkland and Westwold that contains civic number 4748 but the adaptive interpolation interpolates it differently in each locality.

**Comment by alixcote** [comment]
Closing. Will review with address matching using machine learning in the future.
