### ISSUE TITLE
Addresses with glued street name and type receive precision 1

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#179]
Geocoder 4.1. is returning precision 1, score 1 for addresses where there is a missing space between the street name and type.

Examples:
6625 BRANTFORDAVENUE, BURNABY, BC
596 CARDIACLIMB, TAHSIS, BC
9878 156AST, SURREY, BC
15649 84THAVE, SURREY, BC
521 SHORTCLOSE, LADYSMITH, BC

All these addresses score above 90 if the space is added.

**Comment by mraross** [comment]
Any idea how many addresses are like this?

**Comment by bstratto** [comment]
Re: how many addresses fall into this scenario:
I've looked at 2000 addresses from a HLTH file that used to score in the 10's range in 4.0. In 4.1, these addresses score in a wider range given 4.1 improvements. 
From the 2000 addresses reviewed, 194 fall into this scenario. The score varies, as follows:
Score 1: 12
Score above 90: 166
Score between 2 - 89: 16

**Comment by bstratto** [comment]
Further to the above comment:
For the addresses scoring between 2 - 89, there is one example of an address where the lack of space between street name and type caused the geocoder to find the wrong address:
Address: 106 3420 BELLAVE, BURNABY, BC
4.1 result: UNIT 106 -- 3420 Bella-Vista St, Vancouver, BC (score 79, precision 99)
4.1 result if space added: UNIT 106 -- 3420 Bell Ave, Burnaby, BC (score 100, precision: UNIT)

**Comment by alixcote** [comment]
Closing. Will include these examples when testing address matching using machine learning.
