### ISSUE TITLE
unit not echoed when siteName is present, frontGate is absent, and siteName not known

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#183]
In example 2, the second best match should be the best match.

|Example id|input|best match (score matchPrecision)|second best match (score matchPrecision)|link|
|---|---|---|---|---|
|1|UNIT 205 CONDOMINIUMS -- 7555 120A ST, SURREY, BC|UNIT 205 CONDOMINIUMS -- 7555 120A ST, SURREY, BC (90 CIVIC_NUMBER)|UNIT 205 CONDOMINIUMS -- 7555 120 St, Delta, BC (76 BLOCK)|[request](https://geocodertst.api.gov.bc.ca/addresses.html?maxResults=5&addressString=UNIT%20205%20CONDOMINIUMS%20--%207555%20120A%20ST,%20SURREY,%20BC)
|2|CONDOMINIUMS 205 7555 120A ST, SURREY, BC|	7555 120A St, Surrey, BC (97 CIVIC_NUMBER)|UNIT 205 -- 7555 120A St, Surrey, BC (96 CIVIC_NUMBER)|[request](https://geocodertst.api.gov.bc.ca/addresses.html?maxResults=5&addressString=CONDOMINIUMS%20205%207555%20120A%20ST,%20SURREY,%20BC)

**Comment by alixcote** [comment]
Closing. Adding this example to machine learning.
