### ISSUE TITLE
In data integration scripts, BCGNIS localities that are duplicates of DRA localities are being deleted instead of being added as site-localities

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#187]
In address data integration, given a DRA locality of Mill Bay, BC on Vancouver Island and a BCGNIS locality of Mill Bay, BC located near Kincolith in Northern BC, the northern locality is being delete. Instead, add it to the address data as a site locality of Mill Bay -- Kincolith BC.

**Comment by mraross** [comment]
From: Graeme Leeming <gleeming@refractions.net> 
Sent: December 17, 2020 9:36 AM
To: Ross, Michael RA CITZ:EX <Michael.RA.Ross@gov.bc.ca>; Chris Hodgson <chodgson@refractions.net>
Subject: Re: Mill Bay

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.

This all currently happens at the start of the processing pipeline in the FME script that consolidates all custodian site candidates.  I can change the locality duplicating removal logic from all NCAPs to non-BCGNIS NCAPs.  That should produce the scenario you present below.

I don't think there needs to be occupant specific logic related to this ticket as removing the site removes the occupant.  It will, however, require a complete reprocessing at some point.  Chris and I will continue to hold off on any modifications until you are finished testing.  At least this one is easy to fix.

-Graeme
On 2020-12-16 8:30 p.m., Ross, Michael RA CITZ:EX wrote:
You're right. We are trying to purge redundant occupant sites, not redundant bcgnis localities 
Here's the scenario:

Given:
   A DRA locality named Mill Bay
   An occupant and associated site named Mill Bay in Mill Bay, BC
   A BCGNIS locality called Mill Bay near  Kincolit, BC
  
delete the occupant and associated site but keep the BCGNIS locality as Mill Bay -- Kincolit, BC to differentiate it from Mill Bay, BC.

________________________________________
From: Graeme Leeming <gleeming@refractions.net>
Sent: Wednesday, December 16, 2020 6:42 PM
To: Ross, Michael RA CITZ:EX; Chris Hodgson
Subject: Re: Mill Bay 
 
[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.

Hi Michael,

Well I guess I misread the ticket since the examples are all shown with site front gates "--" and not the occupant ones "**".   We also talked about this and decided to apply the logic to all NCAPs (which I could reverse to just apply for GSR sites if we change our mind).

For GSR in particular the address is just a freeform string so occupant links are created when they exactly match on the site name.  If I restore those cases as NCAP sites but removed their occupant counterpart, wouldn't you then get back the originally unwanted Mill Bay -- Ferry Rd, Mill Bay, BC?

-Graeme
On 2020-12-16 6:40 p.m., Ross, Michael RA CITZ:EX wrote:

-->

**Comment by mraross** [comment]
From: Ross, Michael RA CITZ:EX
Sent: Saturday, December 19, 2020 4:11 PM
To: Leeming, Graeme CITZ:IN; (chodgson@refractions.net)
Cc: Kelsey, Brian CITZ:EX; Kelsey, David M CITZ:EX; Brammall, Johnathan CITZ:EX; Stratton, Beatriz CITZ:EX; Newall, Colin G CITZ:EX
Subject: Do we take a step forward or back on subLocalities?
 
Hi Graeme and Chris,

I don't feel comfortable with the current state of subLocalities. We have basically hidden most Indian Reserves and many small towns and villages since no one knows they need to enter a frontGate. The biggest decision to make at our Gold Sprint planning session is whether to take a step back and remove all vestiges of subLocalities, or take a step forward and implement support of both optional frontGate for subLocalities and the new matchPrecision level of SUB_LOCALITY.


Relevent tickets:

https://github.com/bcgov/ols-geocoder/issues/161
https://github.com/bcgov/ols-geocoder/issues/128
https://github.com/bcgov/ols-geocoder/issues/187

**Comment by mraross** [comment]
This should be fixed by issue #191

**Comment by gleeming** [comment]
BCGNIS site processing has been eliminated so those features will no longer contribute candidate site records to the Hybrid batch data.  The logic to remove other NCAPs if they have identical site names to an ITN locality is still in place (to deal with cases like Mill Bay from GSR)

**Comment by cmhodgson** [comment]
As mentioned above, this should be fixed by #191, which is now complete, and I see "Mill Bay in Gingolx, BC" in the current prod geocoder results for "mill bay" (gingolx is beside kincolith). I think we can close this unless I'm missing something.

**Comment by alixcote** [comment]
Thanks @cmhodgson! Closing!
