### ISSUE TITLE
In addresses.html format, add visual separation between each address

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#188]
Its very hard to find the beginning of each address record when scrolling through browser output. Add some kind of visual separation at the end of each address; this could be blank lines, a line of dashes, etc.

**Comment by cmhodgson** [comment]
I will change the link to the list button to the .xhtml output which includes a style for an outline around the tables.

**Comment by cmhodgson** [comment]
This is now fixed in: ols-devkit#176

**Comment by BK01** [comment]
Validated in 4.1 gold release
