### ISSUE TITLE
Overzealous locality garbage removal

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#189]
Given the following address:

     Unit 1 Lynne Valley Care Centre -- 1070 Lynn Valley Rd, North Vancouver BC

the geocoder incorrectly returns the following as the best match:

     Lynn Valley -- District of North Vancouver, BC

instead of this:

     Unit 1 Lynn Valley Care Centre -- 1070 Lynn Valley Rd, District of North Vancouver, BC

**Comment by cmhodgson** [comment]
I needed to limit which parse rules allow locality garbage; input with a front gate should not allow locality garbage. Now done locally.

**Comment by BK01** [comment]
Test results in Geocoder 4.1-Gold (DLV)

Unit 1 Lynne Valley Care Centre -- 1070 Lynn Valley Rd, North Vancouver BC
=>
UNIT 1 LYNNE VALLEY CARE CENTRE -- 1070 Lynn Valley Rd, District of North Vancouver, BC
