### ISSUE TITLE
In addresses resource, add a value property to a fault record 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#19]
Given the following address:

`1175 Douglas St, Saanich, BC`

the geocoder will return the following address:

`1175 Douglas St, Victoria, BC`

and the following  faults:

`"faults":[{"element":"LOCALITY","fault":"isAlias","penalty":1}]`

It would be more helpful to include the aliased locality as follows:

`"faults":[{"element":"LOCALITY","fault":"isAlias","penalty":1,"value":"Saanich"}]`

This enhancement affects the addresses and occupants resources.

needed by Elections BC to get aliased locality a user entered which they are obliged to record under the Elections Act. This approach could also extend to other faulty entered values such as postal code which could be of interest to all clients.

**Comment by gleeming** [comment]
I will need to test if this affects the data prep scripts that batch geocode and canonicalize street names for the site vetting process.  The scoring logic is dependent on interpreting fault patterns, so it may need to be tweaked.  It is possible this could also affect other users that parse out fault details.

**Comment by mraross** [comment]
We could make fault values conditional on a request parameter like  includeFaultValues:Boolean with a default of false for backward compatibility.

**Comment by cmhodgson** [comment]
This is implemented now in my local dev environment, on our next deploy to gazelle we can test the affects on the scripts.

**Comment by gleeming** [comment]
The FME site candidate fault parsing logic is unaffected by this change

**Comment by cmhodgson** [comment]
Presently this change is only output in JSON format - we need to consider if and how we want to output the value in other formats such as CSV and shape. Presently the faults are output in a single field in all other formats, with a structure such as:
LOCALITY.isAlias:1;UNRECOGNIZED.notAllowed:3

I propose a format such as:

Vancouver:LOCALITY.isAlias:1;BACK ALLEY GARBAGE:UNRECOGNIZED.notAllowed:3

It should be noted that any users who are parsing this field from a non-JSON output would potentially be affected by this change. (this includes the FME site candidate logic mentioned above).

**Comment by mraross** [comment]
Is there a format that wouldn't require a change to current parsing? Maybe:

Vancouver:LOCALITY.isAlias:1;UNRECOGNIZED.notAllowed:3;Value:BACK ALLEY GARBAGE

**Comment by cmhodgson** [comment]
We will not add the "value" field to the fault output in formats other than HTML and JSON at this time. This will ensure we do not cause any backward compatibility issues with these other formats.

**Comment by BK01** [comment]
Validated in Geocoder 4.1-Gold (DLV) in JSON, HTML, XHTML for "1175 Douglas St, Saanich, BC"
