### ISSUE TITLE
Locations of Chase and Chase Rural are interchanged.

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#194]
Using the demo app and geocoder 4.1 gold located at:

https://cmhodgson.github.io/ols-devkit/ols-demo/?gc=rri

and the following will be included in the match list:

     Chase BC
     Chase in Chase Rural, BC

If you select Chase in Chase Rural, BC and zoom to it, it is located in downtown Chase. Chase BC is located out in the boonies. Here is a route from Chase BC to Chase in Chase Rural, BC (not the other way round):

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/3da2f4bd-3dea-49bf-96fa-631168c868e9)

**Comment by gleeming** [comment]
In early 2019 GeoBC did a complete rework of the TNRD localities to better refine some regions at a community level.  The original Chase polygon was split into multiple pieces, including new Chase and Chase Rural localities.  After a bit of searching online, it appears that the Village of Chase municipality covers two areas.  One is a small logging landing at the south end of Adams Lake (currently the Chase polygon in ITN and at the green marker in the image above).  The second main portion is near the red marker.  This area is currently contained within a larger Chase Rural locality polygon.

While technically the current Chase locality in ITN represents a small part of the Village of Chase, I think it would be more useful to have it cover the populated portion of the muni (or possibly a multipolygon representing both sections).  I am going to submit a JIRA ticket for GeoBC to review this with authoritative agencies and determine how/if they want to proceed with updating their data.

**Comment by alixcote** [comment]
I think Chase, BC is giving the correct location now. Just not so sure about Chase Rural?

![image](https://github.com/bcgov/ols-geocoder/assets/89096395/c9c7180f-3939-47b3-84ee-3c7edbd45272)

**Comment by gleeming** [comment]
The ITN locality of Chase Rural isn't an official name, so it is not in BCGNIS.  Therefore it's positioning for geocoder is at the polygon centroid for lack of any better option.  It is fairly spread out north/south so I don't really know where a suitable location would be.  However a custom locality-locations entry could be added for this and any other similar case, but would require human intervention to determine that placement.
![image](https://github.com/bcgov/ols-geocoder/assets/21045965/99e132cb-ebe8-4c6b-b0e5-1c0e097b6821)

**Comment by alixcote** [comment]
This is resolved:
![image](https://github.com/bcgov/ols-geocoder/assets/89096395/48aeeb74-fbe0-4237-8ce5-d34c52851e89)
