### ISSUE TITLE
Add Waglisla as a locality alias of Bella Bella

### ISSUE THREAD

**Issue by BK01** [bcgov/ols-geocoder#199]
Details:
http://apps.gov.bc.ca/pub/bcgnws/names/40351.html

Example:
416 Koeye St, Waglisla, BC => 416 Koeye St, Bella Bella, BC

**Comment by BK01** [comment]
Applied and validated in 4.1 Gold release-DLV

**Comment by mraross** [comment]
confirmed in 4.1 gold in dlv and test

**Comment by alixcote** [comment]
Confirmed working. Closing.
