### ISSUE TITLE
Add an occupantName.ignored fault with zero penalty when occupant name is included in a addresses request

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#20]
Given the following addressString in a geocoder.api.gov.bc.ca/addresses request:

StitchNChat Club ** 1175 douglas st, victoria, bc

the geocoder correctly identifies and ignores the occupant name and returns a fullAddress of:
1175 douglas st, victoria, bc

It should also return the following fault with a penalty of 0:

OCCUPANT_NAME_IGNORED

requested by DataBC to improve error reporting for all developers

**Comment by alixcote** [comment]
No client requests right now. Closing until further use case.
