### ISSUE TITLE
Geocoder response: Disclaimer and Privacy URLs

### ISSUE THREAD

**Issue by BK01** [bcgov/ols-geocoder#200]
Changes made to the following URLs via the administration app are not being reflected in the Geocoder response (tested with JSON in DLV (4.1-Gold) and TEST (4.1-Silver)).

1. disclaimer
2. privacyStatement

**Comment by cmhodgson** [comment]
Was the geocoder restarted after the changes were made?

**Comment by BK01** [comment]
Yes the Geocoder was restarted. The restarting of the Geocoder allowed us to verify a newly added locality alias, but the URLs noted above remained unchanged. These fields are present in the DLV and TEST admin app, but not the PROD admin app.

**Comment by cmhodgson** [comment]
Pull request #202 resolves this. It appears those configuration variables were added but the output code was never changed to use them.

**Comment by BK01** [comment]
Once deployed the Geocoder response should include the following.

disclaimer: "https://www2.gov.bc.ca/gov/content?id=79F93E018712422FBC8E674A67A70535",
privacyStatement: "https://www2.gov.bc.ca/gov/content?id=9E890E16955E4FF4BF3B0E07B4722932",

**Comment by alixcote** [comment]
Confirmed these exist in the Geocoder response now. Closing.
