### ISSUE TITLE
Addresses in Australia or text including "Australia" geocoding within BC

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#217]
This issue is to document Geocoder 4.1 handling of alien addresses, specifically from Australia.

**Australian, BC:**
There is a Community named Australian in the Cariboo District. This community has a few roads, such as Perth Rd and Australian Rd.

A number of addresses submitted for geocoding by HealthIdeas are in fact addresses in the country of Australia. Other addresses are simply text such as “, AUSTRALIA, AUSTRALIA, BC”. These addresses are being geocoded to the BC community of Australian.

It appears that some site numbers in Australian are also postal codes in Australia. In a number of addresses, the postal code is provided and the Geocoder takes it for the site number, resulting in 99 precision points.

In the 13+ million HealthIdeas address list, there are:

- 738 addresses geocoding to Australian, BC
- 104 score above 90 and are truly addresses in Australian, BC
- 6 addresses score in the 80s range and appear to be in Australian, BC
- 466 addresses score in the 30-70 range and are addresses in Australia (e.g. “16 RINGTAIL PLACE BRISBANE AUSTRALIA, BRISBANE, BC”) or text such as “PERTH, AUSTRALIA, BC” or “VISITOR BRISBANE, AUSTRALIA, BC”
- The remaining addresses, also in the 30 – 70 range, are addresses in Australia followed by a locality within BC, such as “AUSTRALIA 509 MARQUISS, WHISTLER, BC”

Examples:
addressString | Standardized   address | Score
-- | -- | --
12 REDGUM DR LUGARNO AUSTRALIA, LUGARNO, BC | Australian, BC | 49
122 SIDNAY DR QUEENSALND AUSTRALIA, COOMBABAH, BC | Australian, BC | 49
13 WATERLILY DVE AUSTRALIA, MANDURAH, BC | Australian, BC | 49
22 WATKINWONBAT WAY FAULCONBRIDGE 2776,   AUSTRALIA, BC | Australian Rd, Australian, BC | 50
25 CLIFORD AVE, BISSBANE AUSTRALIA, BC | Australian, BC | 51
NO ADRESS, AUSTRALIA, BC | Australian Rd, Australian, BC | 54
24 SWANLEY ST GOSNELLS 6110, AUSTRALIA, BC | Shanley Rd, Australian, BC | 61
AUSTRALIA AUSTRALIA, AUSTRALIA, BC | Australian Rd, Australian, BC | 66
18 HAVERBRACK AVE, MALVERN 3144 AUSTRALIA, BC | 3144 Australian Rd, Australian, BC | 78
87 WATERMAOOR AVE KILSYTH SOUTH VIC 3137,   AUSTRALIA, BC | 3137 Australian Rd, Australian, BC | 79
AUSTRALIAN CITIZEN, VERNON, BC | Australian Rd, Australian, BC | 34
PERTH AUSTRALIA 4 SEASON HOTEL WHISTLER,   WHISTLER, BC | Perth Rd, Australian, BC | 68

**Melbourne to Shelbourne:**
The addresses below are in Melbourne, Australia. In all cases, precision is 99 and the faults are:
[INITIAL_GARBAGE.notAllowed:3, LOCALITY.missing:10, STREET_NAME.spelledWrong:2, STREET_TYPE.missing:6]

addressString | Standardized   address | Score
-- | -- | --
19 SARSSARUS   DR MELBORNE 3107, MELBOURNE, BC | 3107   Shelbourne St, Victoria, BC | 78
15 ROBINLEE   AVE BURWOOD EAST 3151, MELBOURNE, BC | 3151   Shelbourne St, Victoria, BC | 78
33 SUNNYSIDE   GROVE 3204, MELBOURNE, BC | 3204   Shelbourne St, Saanich, BC | 78
19 DARVIN   KEON PARK 3070, MELBOURNE, BC | 3070   Shelbourne St, Victoria, BC | 78
15 CABINDA DR   KEYSBOROUGH 3173, MELBOURNE, BC | 3173   Shelbourne St, Victoria, BC | 78
2 O CONNOR ST   RESERVIOR 3073, MELBOURNE, BC | 3073   Shelbourne St, Victoria, BC | 78

**False positives with above 90 score:**

addressString | Standardized   address | Score
-- | -- | --
11 CAMDEN   GARDENS SYDNEY AUSTRALIA, NORTH VANCOUVER, BC | 11 Garden Dr,   Vancouver, BC | 91
160 MARCH ST   SYDNEY AUSTRALIA, LAKE COUNTRY, BC | 160 Larch St,   Lake Cowichan, BC | 91
3 BAXTER PLACE   MORLEY W A AUSTRALIA, VANCOUVER, BC | 3 Water St, Vancouver, BC | 91
40 WOODWARD ST MARAWATHER AUSTRALIA,   VANCOUVER, BC | 40 Woodland Dr, Vancouver, BC | 91
6 SAILSBURY CR BOWEN QUEENSLAND   AUSTRALIA, VANCOUVER, BC | 6 Salsbury Dr, Vancouver, BC | 91
22 BARNBY ST MURWILLUMBAH AUSTRALIA,   NANAIMO, BC | 22 Barsby Ave, Nanaimo, BC | 91
120 GORDON AVE HAMILTON SOUTH NEWCASTLE,   AUSTRALIA, BC | 120 Gordon Ave, Quesnel, BC | 90
69 BINGLEY CRES AUSTRALIA, FRASER, BC | 69 Langley Ave, Fraser Lake, BC | 90
20 ELANORA RD   AUSTRALIA NSW, ELANORA HEIGHTS, BC | 20 Glenora Rd, Glenora, BC | 90
135 KING RD   AUSTRALIA, HARKAWAY VICTORIA, BC | 135 King Rd, Salt Spring Island, BC | 90

**Comment by alixcote** [comment]
Closing - added to AI sample documentation
