### ISSUE TITLE
Reject alien addresses currently being returned as false positives

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#221]
Alien addresses are being returned as false positives making it impossible for our major geocoder clients to identify such aliens and send them to an international geocoder. A false positive score 90 or higher, where the addressString is an address that is actually outside BC. The addressString is typically address in an English-speaking country, which increases the chance of street and locality names coinciding with places in BC. In some cases, the addressString contains a BC locality.

Care must be taken to allow waypoint addresses in adjacent jurisdictions for use in the Route Planner (e.g., border crossings, points adjacent to Hwy 97 in the Yukon). For these cases, an additional addresses request parameter may be needed (e.g., rejectAlienWaypoints with default of false to maintain backward compatibility).

Here are some examples:

addressString | Standardized address | Score | Prec. | Faults | Notes
-- | -- | -- | -- | -- | --
271   NEWCASTLE RD NANTWICH CHESHIRE UK, NANAIMO, BC | 271 Newcastle Ave, Nanaimo, BC | 93 | 99 | [LOCALITY_GARBAGE.notAllowed:3,   STREET_TYPE.notMatched:3] |  
2632   11TH AVE EAST SEATTLE WA US, NANAIMO, BC | 2632 11th Ave, Port Alberni, BC | 92 | 99 | [LOCALITY_GARBAGE.notAllowed:3,   LOCALITY.isAlias:4] |  
1001   WILDER AVE HONOLULU HAWAII USA, VANCOUVER, BC | 1001 Kilmer Rd, District of   North Vancouver, BC | 91 | 100 | [LOCALITY_GARBAGE.notAllowed:3,   LOCALITY.isAlias:1, STREET_NAME.spelledWrong:2, STREET_TYPE.notMatched:3] |  
1229   CANTER RD ESCONDIDO CA USA 92027, VANCOUVER, BC | 1229 Salter St, New Westminster,   BC | 91 | 100 | [LOCALITY_GARBAGE.notAllowed:3,   LOCALITY.isAlias:1, STREET_NAME.spelledWrong:2, STREET_TYPE.notMatched:3] |  
329   WOODLAND AVE WADSWOR OHIO US, VANCOUVER B C, BC | 329 Woodland Dr, Vancouver, BC | 91 | 99 | [LOCALITY_GARBAGE.notAllowed:3,   PROVINCE_GARBAGE.notAllowed:2, STREET_TYPE.notMatched:3] |  
7021   WEST DAY FORREST RD EMPIRE MICHIGAN USA, RICHMOND, BC | 7021 West Boulevard, Vancouver,   BC | 91 | 99 | [LOCALITY_GARBAGE.notAllowed:3,   STREET_NAME.partialMatch:1, LOCALITY.isAlias:4] | Could there be a rule to reduce   the confidence of a partial match of street name based on a part of the   street name that is a directionality word? (I.e. matching on words   East/West/North/South could provide a less confident match when there is no   match for the rest of the street name)
36   WHITE AVE NEWTON MASS USA, VERNON, BC | 36 Whitetail Pl, Vernon, BC | 91 | 99 | [LOCALITY_GARBAGE.notAllowed:3,   STREET_NAME.partialMatch:1, STREET_NAME.isAlias:1, STREET_TYPE.notMatched:3] |  
334   HALSBURY CIRCLE GAHANA OHIO USA, VANCOUVER, BC | 334 Salsbury Dr, Vancouver, BC | 91 | 99 | [LOCALITY_GARBAGE.notAllowed:3,   STREET_NAME.spelledWrong:2, STREET_TYPE.notMatched:3] |  
233   WILLIAMS LANE, BIG FORK MT USA, BC | 233 Willis Rd, Big Lake, BC | 91 | 99 | [PROVINCE_GARBAGE.notAllowed:2,   LOCALITY.partialMatch:1, STREET_NAME.spelledWrong:2,   STREET_TYPE.notMatched:3] |  
5290   WESTFIELD CT, LAKE OSWEGO OR USA, BC | 5290 Winfield Rd, Lake Country,   BC | 91 | 99 | [PROVINCE_GARBAGE.notAllowed:2,   LOCALITY.partialMatch:1, STREET_NAME.spelledWrong:2,   STREET_TYPE.notMatched:3] | Could there be a rule to reduce   the confidence of a match when the word being matched is the less descriptive   one in a name (e.g. “Lake” is the less descriptive word in Lake Country and   Lake Cowichan)
903   S4TH AVE, KELSOY WA USA, BC | 903S Fourth St, Nelson, BC | 91 | 99 | [PROVINCE_GARBAGE.notAllowed:2,   LOCALITY.spelledWrong:2, STREET_TYPE.notMatched:3,   CIVIC_NUMBER_SUFFIX.notMatched:1] |  
6606   REXFORD WAY CARMICHAEL CALIFORNIA USA, VANCOUVER, BC | 6606 Telford Ave, Burnaby, BC | 90 | 99 | [LOCALITY_GARBAGE.notAllowed:3,   LOCALITY.isAlias:1, STREET_NAME.spelledWrong:2, STREET_TYPE.notMatched:3] |  
289   VICTORIA ST ALTONA MEADOWS AUSTRALIA, VICTORIA, BC | 289 Victoria St, Salt Spring   Island, BC | 90 | 99 | [LOCALITY_GARBAGE.notAllowed:3,   LOCALITY.isAlias:6] |  
291   VICTORIA DR UK BN20 8XL, EASTBOURNE E SUSSEX, BC | 291 Victoria Dr, Vancouver, BC | 90 | 99 | [LOCALITY_GARBAGE.notAllowed:3,   LOCALITY.spelledWrong:2, LOCALITY.isAlias:4] | Why LOCALITY.isAlias:4, what is   the alias? Is it EASTBOURNE => EAST VANCOUVER?
24   CHESTER SQUARE LONDON UK, REVELSTOKE, BC | 24 Shelter Bay FSR, Revelstoke,   BC | 90 | 99 | [LOCALITY_GARBAGE.notAllowed:3,   STREET_NAME.partialMatch:1, STREET_NAME.spelledWrong:2,   STREET_TYPE.notMatched:3] |  
3   HEIGHTS GREEN LEEDS UK 2711 EMPIRE LANDMARK, VANCOUVER, BC | 3 W 8th Ave, Vancouver, BC | 90 | 100 | [LOCALITY_GARBAGE.notAllowed:3,   STREET_NAME.spelledWrong:2, STREET_DIRECTION.missing:2,   STREET_DIRECTION.notSuffix:0, STREET_TYPE.notMatched:3,   MAX_RESULTS.too_low_to_include_all_best_matches:0] | Could there be a flag to   indicate suspicious matches for results containing many faults? Especially if   the faults are related to the same address component? In this case, 4 faults   in the STREET component could be an indicator of a suspicious match.
4   RIVERSIDE VILLAS PORTSMITH RD SURREY UK, VICTORIA, BC | 4 Dallas Rd, Victoria, BC | 90 | 99 | [LOCALITY_GARBAGE.notAllowed:3,   STREET_NAME.spelledWrong:2, STREET_TYPE.notMatched:3,   STREET_TYPE.spelledWrong:1, STREET_TYPE.notPrefix:0] |  
5 WEST   VIEW CIRCLE, PITTSFIELD SK USA, BC | 5 West Rd, View Royal, BC | 90 | 99 | [PROVINCE_GARBAGE.notAllowed:2,   LOCALITY.partialMatch:1, STREET_TYPE.missing:6] |  
19B   NELSON ST AUSTRALIA, VICTORIA, BC | 19B Nelson St, Quesnel, BC | 90 | 99 | [PROVINCE_GARBAGE.notAllowed:2,   LOCALITY.spelledWrong:2, LOCALITY.isAlias:4,   CIVIC_NUMBER_SUFFIX.notMatched:1] |  
700 W   MAPLE ST MONROE WA USA, VANCOUVER, BC | 700W Maple St, Trail, BC | 90 | 99 | [PROVINCE_GARBAGE.notAllowed:2,   LOCALITY.spelledWrong:2, LOCALITY.isAlias:4,   CIVIC_NUMBER_SUFFIX.notMatched:1] | Likely MONROE was considered a   misspelling of MONTROSE, which is near TRAIL
9091   LINE RD WASHINGTON STATE US, ABBOTSFORD, BC | 9091 Lone Star Rd, Grand Forks,   BC | 90 | 99 | [PROVINCE_GARBAGE.notAllowed:2,   STREET_NAME.partialMatch:1, LOCALITY.isAlias:4, STREET_NAME.spelledWrong:2] |

**Comment by cmhodgson** [comment]
One approach to this would be to look for province/state/country names/abbreviations in the garbage and potentially disallow them or add an extra fault.

**Comment by BK01** [comment]
Closing. Added example to AI documentation.
