### ISSUE TITLE
Postal element is recognized yet  used to generate a standardized address

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#222]
The examples below show addresses that contain only postal element text. Even though the Geocoder does recognize the text as postal element (fault POSTAL_ADDRESS_ELEMENT.notAllowed:1) the text seems to be used to generate a standardized address with precision higher than "PROVINCE".

**Pattern 1 (277 addresses in HealthIdeas):**

AddressString:
•	is <= 15 characters;
•	ends with ‘, BC’;
•	starts with ‘PO BOX’ or ‘, PO BOX’ or ‘, BOX’;
•	characters in positions 7 – 11 are one of “0123456789, OX’;

Examples:
‘PO BOX, 38, BC’ geocodes to BC Harbours Board Rwy, Surrey, BC’
‘, PO BOX X, BC’ geocodes to ‘Cross River, BC’
‘, BOX 1000, BC’ geocodes to ‘BC Harbours Board Rwy, Surrey, BC’

**Pattern 2 (3 addresses in HealthIdeas):**

AddressString:
•	is <= 14 characters;
•	ends with ‘, BC’;
•	starts with ‘GD ‘ or includes ‘ GD ‘;

Examples:
‘, GD STN A, BC’ geocodes to ‘BC Harbours Board Rwy, Surrey, BC’
‘, GD STN, BC’ geocodes to ‘BC’

**Pattern 3 (2 addresses in HealthIdeas):**

AddressString:
•	is <= 15 characters;
•	ends with ‘, BC’;
•	includes ‘COMP ‘;

Examples:
‘, COMP 13, BC’ geocodes to ‘BC Harbours Board Rwy, Surrey, BC’

**Pattern 4 (14 addresses in HealthIdeas):**

AddressString:
•	is <= 15 characters;
•	ends with ‘, BC’;
•	contains a postal code regular expression (with or without the space);

Examples:
‘X9X9X9, N A, BC’ geocodes to ‘A Pier Rd N, Richmond, BC’
‘, V0C2W0, BC’ geocodes to ‘BC Harbours Board Rwy, Surrey, BC’
‘V0H1T0, RO, BC’ geocodes to ‘Road A, Klemtu, BC’

**Comment by BK01** [comment]
Closing. Added example to AI documentation.
