### ISSUE TITLE
Space typo in civic number generates false positive

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#227]
When there is a typo-ed space between the digits of a civic number, the Geocoder standardizes to a numbered street as per the second portion of the typo-ed civic number.

Example:
addressString: 228 6 KITCHENER ST, VANCOUVER, BC
Standardized address: 228 Sixth Ave, New Westminster, BC (score: 90)

The intended address is likely: 2286 Kitchener St, Vancouver, BC

**Comment by cmhodgson** [comment]
I don't know if we can ever handle this. Maybe in the case where the typo has absolutely no other sensible matches, but that would be so rare as to be not worth the effort to fix. I guess we could try to make sure we don't throw out "garbage" that looks too much like a street or locality name, but even then, lots of real garbage such as building or facility names can look a lot like valid street and locality names. You're just not allowed to typo numbers. 

I guess we could just try removing spaces between numbers to see if they got better results... but I can't help but think that will ALSO create false positives, in a much less defendable way.

**Comment by BK01** [comment]
Closing. Added example to AI documentation.
