### ISSUE TITLE
Reserve matchPrecision of SITE for non-civic site addresses only

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#230]
A civic address that happens to have a siteName should not return a matchPrecision of SITE; it should return a CIVIC_NUMBER matchPrecision. SITE should be reserved for addresses that require a siteName to uniquely identify them on a street segment. If an addressString doesn't include a siteName for a civic address that has one, the match result shouldn't include a SiteName.missing fault.  We don't want an otherwise perfect addressString to get penalized because they didn't include vanity names like Casa Del Mar, or Tuscan Village.
If addressString misspells a siteName then a siteName.spelledWrong fault is still appropriate.

**Comment by BK01** [comment]
Validated in Geocoder 4.3.0 using the following NCAP (Johnson Street Bridge -- Victoria, BC). 

https://geocoder.api.gov.bc.ca/addresses.json?addressString=Johnson%20Street%20Bridge%20--%20Victoria,%20BC
