### ISSUE TITLE
53 civic addresses (excluding associated units) have the exact same parcelPoint but are on different streets around Victoria harbour

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#240]
https://geocoder.api.gov.bc.ca/sites/near.xhtml?point=-123.3850335%2C%2048.4224602&maxResults=53&excludeUnits=true&brief=true

**Comment by BK01** [comment]
No longer seeing 53 civic addresses at the same location. However, there are still cases of coincident address points when multiple civic addresses are within a single parcel. The address authority is working on this as a data issue.
