### ISSUE TITLE
Geocoder data integration data flow diagrams

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#243]
Data Flow 1: Shared Geocoder and Route Planner data integration
![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/c875e03b-e01d-4244-948d-f60edb9a948b)

Data Flow 2 - Geocoder data integration
![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/e9202169-36b8-4748-acf8-eef1555fbb72)

Data Flow 3 - Route Planner data integration
![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/f6e0cc51-366d-4847-9373-f47189aed3d8)

**Comment by BK01** [comment]
Closing. New diagrams have been provided to reflect the updated data integration process.
