### ISSUE TITLE
The heart of geocoder data integration

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#246]
Here's an overview of the geocoder data integration process:

| Gather | Transform | _**Integrate**_ | Validate | Deploy

In Gather, we manually download source road network and address data.

In Transform, we transform all source data into standard schemas and format.

In Integrate, we tie addresses to the road network and generate address ranges.

In Validate, we geocode our test address data using the integrated data.

In Deploy,  if the validation was successful, we Deploy the latest data to production.

The Integrate step lies at the heart of the process and our change proposal mostly affects this step so let's take a closer look.  

Geocoder data integration is primarily about tying the latest candidate reference addresses to the latest version of the reference road network (e.g.,  BC Digital Road Atlas) and deriving address ranges. Here is a small portion of the latest DRA and the latest candidate reference addresses:

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/9a80391a-d380-4f4e-a018-1a8bb3d6dcfa)

Each candidate reference address must refer to a road segment in the DRA and that road segment must have a left or right locality name that is identical to the locality name in the candidate reference address. For 2201 Kaslo Creek South Fork Rd, Kaslo, BC, the DRA must have a road segment named Kaslo Creek South Fork Rd_ and the left or right locality name for that road segment must be _Kaslo_

![image](https://user-images.githubusercontent.com/11318574/119045191-fc47bb80-b96f-11eb-80f8-0d08928a5677.png)

The address block assignment process finds the DRA road segment with the same street and locality names as our candidate reference address then creates an access point along the curb of the road segment at the nearest point to the site point.

![image](https://user-images.githubusercontent.com/11318574/119048092-9826f680-b973-11eb-8bd2-4aa4d2c96f25.png)

A candidate reference address is rejected for any of the following reasons:

1. The DRA has no road segment that contains matching street and locality names.
2. There is no matching road segment within 2km of the candidate reference address point.
3. The access line (e.g., a line between the site location and access point) crosses one or more roads.

The address block assignment process is repeated for all remaining candidate reference addresses.

![image](https://user-images.githubusercontent.com/11318574/119048628-58144380-b974-11eb-9913-f973ae75a52d.png)

**Comment by mraross** [comment]
Address ranges are derived from the minimum and maximum civic numbers assigned to each block face. Here's a hypothetical example of civic numbers assigned to three consecutive blocks:

7  11 17 43 99 |                      | 207 217 243 297
----------------| -------------- |--------------------
4 10 18 48 96 |                       |  210 220 240 280

Here are the address ranges expressed as minimum and maximum civic numbers in red in each block:

**1** 7  11 17 43 97 **99** |                      | **201** 207 217 243 297 **299**
----------------| -------------- |--------------------
**2** 4 10 18 48 96 **98** |                       |  **200** 210 220 240 280 **298**

**Comment by BK01** [comment]
Complete. Integrated into the address data pipeline document: https://github.com/bcgov/ols-geocoder/blob/gh-pages/address-data-pipeline.md
