### ISSUE TITLE
Geocoder Data Integration Architecture

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#248]
Data Prep Components Before and After
![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/082b65d9-cc15-43af-9b39-dd0dc6b68215)

Data Gathering
![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/a714c132-e764-41c7-983c-67fa952465c0)

**Comment by BK01** [comment]
Closing. Architecture diagram being updated in local copy of Geocoder data integration docs. Data transformation diagram updated in GitHub.
