### ISSUE TITLE
Some site-name geocoder queries are very slow

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-geocoder#25]
The address:
Lake Cowichan Fire Hall And Ambulance Station -- 3 East North Shore Rd, Lake Cowichan, BC

Takes a very long time (24 sec on current prod, 84 sec on our devel server) to return a result. 

It seems to generate an excessive number of parse derivations (375,877) which then become 847,820 matches, which is reduced to 34,730 after removing duplicates.

There are other examples of slow site-name based queries but this is the worst one found so far.

needed by all clients improve worst case performance and user experience

**Comment by cmhodgson** [comment]
This has been fixed by a combination of changes to the parser and matcher:
1) implementing a multi-pass process that first runs with no spell-correcting, and only attempts spell correcting after that if no match of at least 90 points is found
2) removed the unrecognized handling heuristic which tried throwing out each word in turn
3) changed the match handling to maintain a priority queue of the best matches found, ordered by score, using a min heap, which also prevents add duplicate matches, and is limited in size to the query's maxResults +1  - this means that much less memory is used in cases where many parse derivations and matches are found, as we don't keep them all in memory (we previously did and sorted/unique'd them afterward)
4) the changes that try to prevent locality hopping also reduce the number of match candidates found

**Comment by BK01** [comment]
Validated improved execution time (328.044) in Geocoder 4.1-Silver (TEST):
Lake Cowichan Fire Hall And Ambulance Station -- 3 East North Shore Rd, Lake Cowichan, BC
