### ISSUE TITLE
unitNumberSuffix in structured address causes match failure  

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#251]
For an address with a known unitNumber and unitNumberSuffix, using addressString works:

UNIT 203A 815 MICHEL RD ELKFORD BC

https://geocoder.api.gov.bc.ca/addresses.xhtml?addressString=815%20Michel%20Rd%20UNIT%20203A%20Elkford%20BC

 Same address using individual address elements doesn’t work:

https://geocoder.api.gov.bc.ca/addresses.xhtml?unitDesignator=UNIT&unitNumber=203&unitNumberSuffix=A&civicNumber=815&streetName=Michel&streetType=Rd&localityName=Elkford&provinceCode=BC

Known unit
UNIT 103C 4678 ELK LAKE DR SAANICH BC

https://geocoder.api.gov.bc.ca/addresses.xhtml?unitDesignator=UNIT&unitNumber=103&unitNumberSuffix=C&civicNumber=4678&streetName=Elk%20Lake&streetType=Dr&localityName=Saanich&provinceCode=BC

**Comment by BK01** [comment]
Validated with Geocoder 4.2.0-SNAPSHOT (geocodertst.api.gov.bc.ca)
