### ISSUE TITLE
Save manually-corrected,rejected addresses for use as training data for learning algorithms in future address parsers

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#257]
Our clients always want better address matching. Geocoder v4.1 achieved a 20% improvement, yet our major clients send us rejected addresses and ask if they can be better handled in the next release. The first step in parser improvement is reject analysis, looking for patterns in bad data. As part of this analysis, whenever we manually correct an address, we should save the rejected address and its corrected version for use as training data for learning algorithms.

**Comment by BK01** [comment]
Closing. Will include these examples when testing address matching using machine learning.
