### ISSUE TITLE
Add support to geocoder and data-prep for new ITN local/express ferry classes

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#26]
BC Ferries promised to refine their ferry classes. When these new classes make their way into ITN, geocoder prep will need to made aware of them.

**Comment by cmhodgson** [comment]
Doesn't this belong in ols-router, if anywhere? I don't think that ITN added these yet.

**Comment by mraross** [comment]
You're right. BC Ferries promised to restructure the ferry routes  so its a future thing which is why I took it out of this year's work. I thought it would apply to both Geocodable BC Maker and Routable BC Maker.

**Comment by alixcote** [comment]
Closing for now.
