### ISSUE TITLE
Add mall names to malls with civic addresses

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#266]
parcelPoints for gov service delivery locations in shopping malls such as pharmacies, med clinics and labs won't be near the actual storefront location so it will be useful to have mall name in siteName of all malls  that have civic addresses to let people know the address is a mall and the location is approximate. 

Here is an example:
Kingsgate Mall -- 370 East Broadway, Vancouver, BC

Here is a  list of all malls in BC
https://www.shopping-canada.com/shopping-malls-centers/british-columbia

**Comment by BK01** [comment]
Will re-open if there is a client need.
