### ISSUE TITLE
Automate geocoder data integration process

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#3]
**What is Geocoder Data Integration?**
Here's an overview of the geocoder data integration process:

**Gather** | **Transform** | _**Integrate**_ | **Verify** | **Deploy**

In Gather, we download source road network and address data.

In Transform, we transform all source data into standard schemas and formats and do field-level validation.

In Integrate, we tie addresses to the road network and generate address ranges.

In Verify, we verify the quality of the integrated data by geocoding our Acceptance Test addresses.

In Deploy, if the validation was successful, we deploy the integrated data to a given geocoder environment.
<br>
**Weaknesses of current implementation**

The current geocoder data integration process has three main weaknesses:

- It is too fussy. The current process requires many manual steps that require careful typing and lots of visual confirmation.
- It takes too long. It takes approximately three business days to complete.
- It ties up our delivery and test environments; conversely, delivery and testing of code fixes and enhancements often blocks the data integration process. We rarely keep to our stated monthly data update schedule.

**Business Value**
Currently, authoritative addresses are submitted to us monthly but we have not been able to prepare them for use in the geocoder on that schedule. This means our users (e.g., MCFD, Elections BC) are submitting addresses of new construction that the geocoder doesn't know about or addresses for which the authoritative location has been improved but the geocoder doesn't know about either. We are also receiving an updated road network (Integrated Transportation Network) on a monthly basis.

Automating the geocoder data integration process will allow Location Services to maintain a monthly update schedule and respond to emergency updates in a timely fashion (e.g., one or two days). It will shorten the data integration process from days to hours. Note that a change to the road network necessitates a geocoder data integration (e.g., due to potential road segment name changes).

[Here](https://github.com/bcgov/ols-geocoder/blob/gh-pages/address-data-pipeline.md) is more details on the geocoder data integration process,

**Comment by alixcote** [comment]
Already working on this with more detailed tickets.
