### ISSUE TITLE
Batch Geocoder - Add yourId to errorResultData

### ISSUE THREAD

**Issue by BK01** [bcgov/ols-geocoder#309]
errorResultData files generated by the Batch Geocoder contain the following fields.

-sequenceNumber
-errorCode
-message
-trace

Is it possible to also include the yourId field (if provided by user)?

**Comment by cmhodgson** [comment]
I don't believe I have any control over the fields output in the errorResultData files. The format of these files is shared across all CPF plugins, and the "yourId" field is something that we implemented in the geocoder CPF plugin logic. I sure there are ways this could be done, but it would require changes to the CPF, first.

**Comment by BK01** [comment]
Closing. Will re-open if there is a client need.
