### ISSUE TITLE
Geocode of Addresses resolve to the same point

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ols-geocoder#327]
I geocoded this using the Batch Geocoder.
* A couple of these are addresses that are close together, however my expectation is that they would have different points.
* In other cases the addresses are on different streets and resolve to the same point.

**Question**
* Is this a data issue? I suspect the addresses come from Occupants as they are government buildings.
* Is this an issue with how points are assigned?

addressString | associated_point | Google Maps point |  
-- | -- | -- | --
525 Superior St, Victoria, BC | -123.3708218 48.4176982 | -123.37120722463482   48.41801605861786 |  
545 Superior St, Victoria, BC | -123.3708218 48.4176982 | -123.3703003442296   48.41814983298842 |  
501 Belleville St, Victoria, BC | -123.3706025 48.4194604 | -123.37032791724232   48.41979498913853 | Legislature Building
421 Menzies St, Victoria, BC | -123.3706025 48.4194604 | -123.37188481436985   48.41894691787952 |  
612 Government St, Victoria, BC | -123.3706025 48.4194604 | -123.36933925957132   48.41895749207098 |  
431 Menzies St, Victoria, BC | -123.3706025 48.4194604 | -123.37160109952852   48.41912742315507 |  
620 Superior St, Victoria, BC | -123.3678164 48.4188591 | -123.36736011154849   48.41883306233498 |  
617 Government St, Victoria,   BC | -123.3678164 48.4188591 | -123.36846430190039   48.41905873018766 |  
940 Blanshard St, Victoria, BC | -123.3639041 48.4232168 | -123.36392185481665   48.42364578356965 |  
735 Broughton St, Victoria, BC | -123.3639041 48.4232168 | -123.36387781539399   48.423380856676296 |  
506 Government St, Victoria,   BC | -123.3692576 48.4176864 | -123.36926949037672   48.417496943921165 |  
563 Superior St, Victoria, BC | -123.3692576 48.4176864 | -123.36930121305525   48.418178038945065 | QP
2955 Jutland Rd, Victoria, BC | -123.3782747 48.4394906 | -123.37836805275252   48.43945020206609 |  
2957 Jutland Rd, Victoria, BC | -123.3782747 48.4394906 | -123.37864074603065   48.43962848001249 |  
634 Humboldt St, Victoria, BC | -123.3664496 48.4230547 | -123.36667360085691   48.42270013261792 |  
808 Douglas St, Victoria, BC | -123.3664496 48.4230547 | -123.36631060190035   48.4227923986975 |  
1106 Cook St, Victoria, BC | -123.3544327 48.4237019 | -123.354227459571   48.423849214623594 |  
1084 Fort St, Victoria, BC | -123.3544327 48.4237019 | -123.3546848884066   48.42377179506385 |

**Comment by dkelsey** [comment]
Related to #224

**Comment by BK01** [comment]
Closing. Determined to be a source data issue. Have spoken to the City of Victoria about the issue.
