### ISSUE TITLE
https server 500 error in response to sites/nearest.geojson request

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#34]
@mraross commented on [Thu May 23 2019](https://github.com/bcgov/api-specs/issues/372)

https://geocoder.api.gov.bc.ca/sites/nearest.geojson?locationDescriptor=accessPoint&maxDistance=5000&excludeUnits=true&onlyCivic=true&brief=true&point=-127.28111966701108,49.65348852775016

---

@cmhodgson commented on [Fri May 24 2019](https://github.com/bcgov/api-specs/issues/372#issuecomment-495740726)

The error handler was not setup to handle geojson output (even though it is the same actual output as json). Had to add the geojson mime type to the ErrorMessageConverter's supported types. This is fixed locally and ready for future delivery.

**Comment by cmhodgson** [comment]
This is fixed now.

**Comment by BK01** [comment]
DataBC will QA shortly when 4.0 is deployed in DLV.

**Comment by mraross** [comment]
Verified in delivery using:
https://geocoderdlv.api.gov.bc.ca/sites/nearest.geojson?locationDescriptor=accessPoint&maxDistance=5000&excludeUnits=true&onlyCivic=true&brief=true&point=-127.28111966701108,49.65348852775016
