### ISSUE TITLE
Make logging configurable using environment variables

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-geocoder#36]
Previously, log4j properties files were selected base on the environment the package was built for. The environment-specific packaging has been removed in favor of environment variable based configuration which works better within docker containers on k8s. The logging configuration should be done in the same way, likely with 2 env. variables for location and level. Perhaps we can switch to logback or log4j2 for output, especially if it makes this configuration easier. Logging actions would remain based on slf4j as always.

**Comment by alixcote** [comment]
Closing. No recent need for changes to logging.
