### ISSUE TITLE
Unstructured /addresses request with a locality filter

### ISSUE THREAD

**Issue by BK01** [bcgov/ols-geocoder#363]
Investigate the idea of adding a localities parameter that can be used to limit the search results (using an unstructured address) to the locality or localities provided.

for example:
https://geocoder.api.gov.bc.ca/addresses.json?addressString=100 Main Street&localities=Vancouver
or
https://geocoder.api.gov.bc.ca/addresses.json?addressString=100 Main Street&localities=Penticton

This would be similar to the localities parameter seen in the Batch Geocoder which is described as a 'Comma-delimited list of acceptable locality names; matches not in a locality in this list will not be returned.'

**Comment by cmhodgson** [comment]
Brian, how is this different from the existing localities filter?

**Comment by BK01** [comment]
You can disregard this issue, as it looks like we can satisfy the request with the existing parameters. We were also thinking about expanding the filter concept to potentially also include other address elements such as street name. We closed the issue as it may suffice as-is by using either the localities parameter or notLocalities parameter (along with maxResults for additional review).
