### ISSUE TITLE
Locality Names do not include punctuation from GNIS

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-geocoder#365]
The new Java based data processing pipeline is not outputting the "more correct" version of locality names from GNIS.

**Comment by cmhodgson** [comment]
PR #358 was the fix for this issue, PR #366 now supports both the old and new column names as this seems to be a recurring problem.

**Comment by cmhodgson** [comment]
Brad I will let you close this if you are happy that this is resolved.

**Comment by brad-sparks-gov-bc-ca** [comment]
Chris - this Java update worked great, tested both versions of the BCGNIS file, I will close this ticket, and also let Mike deal with the PR 366.
