### ISSUE TITLE
geocoder json/geojson output, add a flag not to display null fields

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#41]
@ll911 commented on [Thu Oct 11 2018](https://github.com/bcgov/api-specs/issues/349)

geocoder json/geojson output, add a flag not to display null fields 
e.g. `nullFields=false`

All clients need this to reduce result payload size and improve user experience

**Comment by alixcote** [comment]
Brief=true parameter reduces the payload size. This one can be closed.
