### ISSUE TITLE
Add sites/within/random which returns a number of sites chosen at random

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#43]
@mraross commented on [Mon Dec 18 2017](https://github.com/bcgov/api-specs/issues/265)

has same parameters as sites/within. This is currently implemented in the Location Services in Action and has proved so useful in QA and outreach, it should be in API for all to benefit.

needed by DataBC to support QA,  outreach, and geocoder evaluations by prospective clients.

---

@mraross commented on [Tue Feb 13 2018](https://github.com/bcgov/api-specs/issues/265#issuecomment-358487414)

Instead of a maxDistance parameter, the resource could autocalibrate maxDistance as follows:

if there is only one civic addresses within bbox then return civic address endif

if there are no civic addresses then return error "No civic addresses within requested bbox" endif

Try 10 random point searches with maxDistance=randomRadius (metres)
if civic address found then return civic address endif

Try 10 random point searches with maxDistance=randomRadius *10 (metres)
if civic address found then return civic address endif

Try 80 random point searches with maxDistance=randomRadius * 100 (metres)
if civic address found then return civic address endif

Return error "No civic address found"

---

@mraross commented on [Tue Feb 13 2018](https://github.com/bcgov/api-specs/issues/265#issuecomment-365371010)

Instead of the resource parameter &xmdx, add support for a global config variable called randomRadius that has a default value of 30 (metres) and can be managed from the geocoder admin app. randomRadius should be restricted to a value between 10 and 90.

**Comment by alixcote** [comment]
Internal request. No client requests at this time. Kind of done in the demo app and can be handled with client business logic.
