### ISSUE TITLE
Add support for a data vintage date

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#53]
@mraross commented on [Thu Jan 11 2018](https://github.com/bcgov/api-specs/issues/280)

Having a data vintage date that is shown in api responses will allow users to know the vintage of the data the current geocoder/router is using.

Graeme suggests the data prep process generate an additional file with vintage data information in it which will be read in by geocoder and route planner nodes on startup.

Options

1. Single or multiple vintage dates: 
    - data_vintage
    - data_vintage + dra_vintage, addressbc_vintage, bca_vintage, opendata_vintage, statscanrnf_vintage

2. How is vintage represented in API?
    - as new HTTP headers of existing resources
    - in response metadata of existing resources with code version and execution time, etc.
    - in a response to a new dataVintage resource request 

---

@cmhodgson commented on [Fri Feb 09 2018](https://github.com/bcgov/api-specs/issues/280#issuecomment-364552263)

After a discussion we decided that the updated date on sites should be used to store the source data vintage date for the source the site came from,

**Comment by BK01** [comment]
Complete. Represented in the response from geocoder.api.gov.bc.ca as baseDataDate. 

Example:
"baseDataDate": "2024-07-04T20:25:37Z"
