### ISSUE TITLE
in geocoder, add a resource that represents the service area for a given occupant and occupant type

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#55]
@mraross commented on [Tue Mar 21 2017](https://github.com/bcgov/api-specs/issues/165)

/geocoder/occupants/serviceAreas/{serviceType}/{serviceCentreId} 

will return all of the occupant properties as well as the additional service centre properties. Where the {serviceType} is specified by the tag used in GSR to identify the type of service offered by the centre.

     - service area population estimate
     - service centre location point (as part of occupant details)
     - total distance of population to service centre
     - total road network length

Service area population estimates are aggregation of DRA block population estimates which can be sourced from StatsCan under an OGL license.

The type parameter will be used in a tag search for an internally created and managed type tag (e.g., occupantType:firehall)

Internally make ServiceCentre a subclass of occupant with the additional service centre (area) properties.

---

@mraross commented on [Wed Apr 26 2017](https://github.com/bcgov/api-specs/issues/165#issuecomment-297529546)

All service area properties should be statically computed during offline data prep.

---

@cmhodgson commented on [Tue May 30 2017](https://github.com/bcgov/api-specs/issues/165#issuecomment-305029463)

dependent on #193

**Comment by alixcote** [comment]
Service areas and census data are in the BCGW. 
Can use GIS software or Geoserver API to overlay/calculate data. 
Service areas better to come from BCGW instead of GSR.
