### ISSUE TITLE
Generate non-civic addresses for all natural features

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#57]
@mraross commented on [Fri Aug 19 2016](https://github.com/bcgov/api-specs/issues/33)

 Generate NCA's for all lakes, islands, etc.. Use fresh water atlas to compute bbox

**Comment by alixcote** [comment]
Older ticket, no known use cases. Also, BCGNWS provides a lat/log for natural features. ie: https://apps.gov.bc.ca/pub/bcgnws/names/9457.html

Closing.
