### ISSUE TITLE
Add brief parameter support to batch geocoder cpf plugin

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#60]
brief is missing from the application parameters list in the batch geocoder job submission form.

**Comment by cmhodgson** [comment]
Brief doesn't make sense for the batch geocoder for two reasons:
1) we can't change the output data structure in CPF
2) why would you run a batch and not want the full output? The brief version is primarily intended to reduce data transmission for the interactive web app.

**Comment by mraross** [comment]
Agreed.
