### ISSUE TITLE
Add common truck destinations to geocoder as non-civic addresses

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#62]
Add common truck destinations such as Westshore Terminals and Delta Port to Geocoder data exception file for inclusion in February address data integration. This will allow users of the TL CVRP application to enter destination names and have them autocompleted by the geocoder.

Destinations should be in one of the following forms:

**name,locality,provinceCode,lat,lon**

**name,street,locality,provinceCode,lat,lon**

where **name** is destination name (e.g., Delta Port)

**street** includes street name, street type, street direction but does not include civic number or unit number (e.g., Roberts Bank Rd)

**locality** is the municipality or town name that contains the destination point (e.g., Delta)

 **provinceCode** is the two-letter province code (e.g., BC)

**Comment by mraross** [comment]
@al-tabb If you provide the list of common destinations, I will ensure it gets added to the list of geocoder reference addresses. Here's an example list:

Westshore Terminals,Roberts Bank Rd,Delta,BC,49.017,-123.64
Delta Port Terminal, Roberts Bank Rd,Delta,BC,49.022,-123.157

**Comment by al-tabb** [comment]
@gk-tl Can you provide a list of 'common' origin destinations with an approximate location (cross streets, description, screenshot).  I can then provide the lat long for these.

**Comment by mraross** [comment]
@gk-tl If needed, the geocoder can support separate, named entrance and exit points as in:

CenTerm  Terminal Entrance,Centennial Rd,Vancouver, BC,lat,lon
CenTerm Terminal Exit,Centennial Rd,Vancouver,BC,lat,lon

**Comment by gk-tl** [comment]
Goods start would be port access - see attached document
[2020-01-21 TRP Port Access Routes.docx](https://github.com/bcgov/ols-geocoder/files/4196638/2020-01-21.TRP.Port.Access.Routes.docx)

**Comment by gk-tl** [comment]
CN Intermodal in Surrey:
https://www.google.ca/maps/@49.1923629,-122.7386282,474m/data=!3m1!1e3?hl=en

CP Intermodal in Pitt Meadows:
https://www.google.ca/maps/place/Canadian+Pacific+Railway,+Vancouver+Int.+Facility/@49.2442278,-122.7288029,947m/data=!3m1!1e3!4m8!1m2!2m1!1scp+intermodal!3m4!1s0x0:0x9511e9dbda5f9b36!8m2!3d49.2428412!4d-122.7252299?hl=en

Vircually any business on Annacis Island:
https://www.google.ca/maps/place/YVR2+Amazon+Canada+Fulfillment+Services/@49.1683565,-122.954323,1897m/data=!3m1!1e3!4m5!3m4!1s0x5485d8d7189bbc37:0xf4cc50e72146c15a!8m2!3d49.1609089!4d-122.9493767?hl=en

Ditto for business in Blundell Area (AKA the Richmond Logsitics Hub), including:
Ikea Distribution Centre: https://www.google.ca/maps/place/IKEA+Distribution+Services+%E2%80%93+Vancouver/@49.1537913,-123.0368492,3795m/data=!3m1!1e3!4m5!3m4!1s0x0:0x5a2074092b3f5f59!8m2!3d49.1586532!4d-123.04187?hl=en

Coast 2000 Terminals: https://www.google.ca/maps/place/Coast+2000+Terminals/@49.1537913,-123.0368492,3795m/data=!3m1!1e3!4m5!3m4!1s0x5485df72f0460b2d:0xdc84170f6cb258e6!8m2!3d49.1479522!4d-123.0453515?hl=en

Lafarge: 
https://www.google.ca/maps/place/Lafarge+Canada/@49.1594847,-123.0069959,474m/data=!3m2!1e3!4b1!4m5!3m4!1s0x5485df14522f41dd:0x3e9156cbd5c60402!8m2!3d49.1594847!4d-123.0048072?hl=en

Adesa:
https://www.google.ca/maps/place/ADESA+Vancouver/@49.160495,-123.0229175,949m/data=!3m1!1e3!4m5!3m4!1s0x5485df6e6ae87847:0x14891d5623950e45!8m2!3d49.162277!4d-123.0242425?hl=en

All produce wholesaler along "Produce Row" in CoV:
Freshpoint, Van-Whole Produce, The Procue Terminal etc:
https://www.google.ca/maps/place/FreshPoint+Vancouver/@49.2739545,-123.0896616,473m/data=!3m1!1e3!4m5!3m4!1s0x54867169f8acee43:0x68b466734361e1a7!8m2!3d49.2728768!4d-123.0826027?hl=en

Sysco in Port Coquitlam (and logistics/transport companies in the surrounding area (Kingsway between Mary Hill Bypass & Kelly Ave, Broadway Street between Kingsway and Mary Hill Bypass, businesses along May Hill Bypass by the Fraser River, starting at Broadway to Hwy 7 Interchange).
 
https://www.google.ca/maps/place/Sysco+Vancouver/@49.2479848,-122.7548897,947m/data=!3m1!1e3!4m5!3m4!1s0x5485d5e14fe0d3bd:0x28ec5f1d2bfa7fde!8m2!3d49.2475207!4d-122.7512982?hl=en

https://www.google.ca/maps/place/Valiant+Log+Sort+Ltd/@49.2498477,-122.7408993,861m/data=!3m1!1e3!4m5!3m4!1s0x5485d5e83e0b972b:0xe3150891ffcd431!8m2!3d49.2481336!4d-122.7373642?hl=en

Maple Ridge - off Hwy 7 by Fraser River:
https://www.google.ca/maps/place/Lafarge+Canada+Inc/@49.1879412,-122.5738728,862m/data=!3m1!1e3!4m5!3m4!1s0x5485d2e1d6f1f341:0x8280c4c8c4b81487!8m2!3d49.1863476!4d-122.567524?hl=en

Rempel Bros Concrete (and businesses in surrounding area) in TOL:
https://www.google.ca/maps/place/Rempel+Bros,+Langley+plant%232/@49.1166809,-122.6633815,1727m/data=!3m1!1e3!4m5!3m4!1s0x5485d1d7b9331bd1:0x4ac37823493b3c71!8m2!3d49.1171444!4d-122.6526312?hl=en

Campbell Heights Industrial Area (along 192 Street between 20th Ave and 40 Ave)
https://www.google.ca/maps/place/Loblaw+South+Surrey/@49.053792,-122.7007393,3459m/data=!3m1!1e3!4m5!3m4!1s0x5485c59f1ecfaa19:0xffdbb448ddb1a052!8m2!3d49.0520962!4d-122.6986277?hl=en

CBSA Pac Hwy (Origin for trip to LM)
https://www.google.ca/maps/@49.0033989,-122.7362464,433m/data=!3m1!1e3?hl=en

Truck Staging Plaza to US CBP (destination for trip from LM))
https://www.google.ca/maps/@49.0033989,-122.7362464,433m/data=!3m1!1e3?hl=en

YVR Area, including:
https://www.google.ca/maps/place/FedEx+Ship+Centre/@49.1887226,-123.157155,508m/data=!3m1!1e3!4m5!3m4!1s0x548674d3c03d35c7:0x1229fbd6ebacb270!8m2!3d49.1879691!4d-123.1557485?hl=en

https://www.google.ca/maps/place/Purolator/@49.1887226,-123.157155,508m/data=!3m1!1e3!4m5!3m4!1s0x0:0xe5784fa7d9cfaf07!8m2!3d49.188524!4d-123.1576234?hl=en

Brunette River Industrial Area in New West:
https://www.google.ca/maps/place/Sokil+Express+Lines+Ltd/@49.2272229,-122.8881667,1015m/data=!3m1!1e3!4m5!3m4!1s0x54867806c4731a5d:0xfd8fe6e11e99ce2d!8m2!3d49.2264053!4d-122.8807805?hl=en

United Boulevard Industrial Area in Coquitlam:
https://www.google.ca/maps/place/Fast+Freight/@49.2301524,-122.8582812,4059m/data=!3m1!1e3!4m5!3m4!1s0x0:0xf32247294b041dd0!8m2!3d49.2262722!4d-122.8467607?hl=en

Industrial Area between Fraser Surrey Docs and Scott Rd. in Surrey:
https://www.google.ca/maps/place/Frito+Lay+Canada/@49.1907235,-122.9066799,3449m/data=!3m1!1e3!4m5!3m4!1s0x410b81f6ed98ddcd:0xd8ba9c6cf529e397!8m2!3d49.1927078!4d-122.8949855?hl=en

Businesses along Timberland Road in Surrey:
https://www.google.ca/maps/place/RDM+Enterprises+Ltd/@49.199873,-122.8944383,862m/data=!3m1!1e3!4m5!3m4!1s0x5485d8153cb75775:0xfe569ff55db222ef!8m2!3d49.2002678!4d-122.8922698?hl=en

Port Kells Industrial Area in Surrey (pretty much all businesses here):
https://www.google.ca/maps/place/Surrey+Transfer+Station/@49.1767442,-122.6973681,2901m/data=!3m1!1e3!4m5!3m4!1s0x5485d15b07196171:0x2e2122de9baefb0e!8m2!3d49.1805699!4d-122.6868367?hl=en

**Comment by mraross** [comment]
@gk-tl Thanks Greg.
@al-tabb take it away Al.

**Comment by al-tabb** [comment]
@mraross I just had a chat with Greg and we decided that some of the locations in Greg's list are out of scope as we could not accurately determine the appropriate truck entrance/exit.  I will add a select list with lat/longs shortly.

**Comment by gk-tl** [comment]
@al-tabb @mraross 

Site specific traffic circulation (i.e., permitted truck entry/exit points, routes, and restrictions on a given property) is not something TL can readily identify. We would need input from the property owner. Exception to this is Port access and select sites such as CN/CP inter-modal facilities, where it is relatively easy to pin-point truck access gates.

**Comment by mraross** [comment]
that's fine with us. Just wanted you to know that level of precision is available if you need it.

**Comment by al-tabb** [comment]
CN Intermodal, Surrey, BC, 49.191392, -122.734751
CP Intermodal, Pitt Meadows, BC, 49.244297, -122.724663
Coast 2000 Terminals, Richmond, BC, 49.148071, -123.045520
Vanterm, Stewart St, Vancouver, BC, 49.284965, -123.073932
Centerm, Vancouver, BC, 49.285541, -123.089350
Delta Port Entrance, Roberts Bank Way, Delta, BC, 49.022400, -123.157649
Delta Port Exit, Roberts Bank Way, Delta, BC, 49.023082, -123.159323
Fraser Surrey Docks, Elevator Rd, Surrey, BC, 49.183675, -122.909414
Lynnterm West Gate, Brooksbank Ave, District of North Vancouver, BC, 49.305154, -123.040604
Lynnterm East Gate, Mountain Hwy, District of North Vancouver, BC, 49.301132, -123.032171
Univar Canada Ltd., Mountain Hwy, District of North Vancouver, BC, 49.301132, -123.032171
Chemtrade Chemicals, Armherst Ave, District of North Vancouver, BC, 49.301255, -123.015951
Wallenius Wilhelmsen Logistics, Dock Rd, Delta, BC, 49.184741, -122.929563
Richardson International, Low Level Rd, District of North Vancouver, BC, 49.307796, -123.052454
Cargill Terminal, Low Level Rd, District of North Vancouver, BC, 49.307796, -123.052454
Neptune Bulk Terminal, Low Level Rd, District of North Vancouver, BC, 49.307796, -123.052454

**Comment by mraross** [comment]
@al-tabb Thanks for the nca list. Are the last three entries supposed to have the exact same coordinates>

**Comment by al-tabb** [comment]
@mraross The last two have the same entrance.  I've just edited Richardson International as I discovered it does have a different entrance

**Comment by mraross** [comment]
Great, thanks for checking and the quick turnaround.

**Comment by mraross** [comment]
Verified in production

**Comment by mraross** [comment]
Delta Port Terminal is on Roberts Bank Rd, not Roberts Bank Way.

**Comment by gk-tl** [comment]
According gmaps, it's Roberts Bank Way: 
https://www.google.ca/maps/@49.029408,-123.149756,15.96z?hl=en

**Comment by gleeming** [comment]
From online searches, it looks like Roberts Bank Centre is at 1 Roberts Bank Way and GCT Deltaport is at 2 Roberts Bank Way.  I have submitted a JIRA ticket for GeoBC to research and update ITN since that street name is currently not in the road data.  They have it as Roberts Bank Rd with addressing covering 0-4.
