### ISSUE TITLE
Handle detached suffix on a numbered street name

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#66]
Users sometimes enter:

     102 A St

 instead of:

     102A St

Teach parser how to recognize and fix this case.

**Comment by cmhodgson** [comment]
This sort of logic is already in place for civic numbers and civic number suffixes; however street names are made up of "street name words" some of which may be numbers or suffixes, but we don't presently consider them as such. It should be possible to add this logic.

**Comment by cmhodgson** [comment]
I think the best way to handle this is to add street aliases from eg. "102 A St" (with a space) to "102A st" (no space) - similarly to glued words cases like sea <space> ridge vs. "searidge".

**Comment by cmhodgson** [comment]
I've changed my mind, I want to handle this in the parser. Previously, any input words with letters and numbers combined where left as a single token, which is later interpreted as number and affix in specific cases (civic number and affix). I think this needs to be generalized for all cases, which is best done by separating letters and numbers into separate words/tokens on input, and also normalizing all base data in the same way , eg. street names, unit numbers, etc. As it is now, the base data includes street names as both "100A" and "100 A", which only match if the input exactly matches them. 

Going forward I intend to normalize them both as "100 A" but still return the "official" version as it comes from ITN/DRA. Only input that includes numbers followed by letters, or letters followed by numbers, will be split in this way, cases of more complicated codes eg. A1A or 1A1 which include multiple number-letter transitions will not be broken up. This will also require changing the way that ordinals are handled, eg. 5th would become "5 th", but instead the ordinal will be thrown out at the lexing stage. This will also help with #13 unit number stuck to unit designator.

**Comment by mraross** [comment]
I agree with this approach. It will also allow the parser to correctly handle a street called A. For example:

     201 A Ave, Kaslo, BC

**Comment by cmhodgson** [comment]
This is done. Note that the roads named "A" are somewhat annoying as a simple street only input like 201A or 51A (now with or without the space) will match to those A roads before the street with same name as it is a more precise match.

**Comment by mraross** [comment]
Verified in v4.1 gold in test using 102 A ave surrey bc.
