### ISSUE TITLE
Verify point batch geocoded address output coordinates in requested map projection

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#75]
1. Start up batch geocoder
2. Submit the following list of addresses and request geojson output in EPSG:4326 projection
   https://raw.githubusercontent.com/bcgov/ols-geocoder/gh-pages/sites_bc.csv
3. Download result file and load geojson into geojson.io
4. Visually verify locations

**Comment by BK01** [comment]
Test completed successfully with CPF 5.1.3 and BGEO 3.4.2 in TEST & PROD.
This test has also been added to the LOC test outline.

**Comment by mraross** [comment]
Verified in delivery using CPF  and BGEO 

![image](https://user-images.githubusercontent.com/11318574/83302779-c33b9780-a1b0-11ea-842f-851fe0fa9598.png)

**Comment by mraross** [comment]
Verified in v4.1 Gold in delivery.

**Comment by mraross** [comment]
Verified in v4.1 Gold in production
