### ISSUE TITLE
Update online geocoder to support new architecture

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#78]
Software developer to adapt online geocoder to the cloud-ready architecture defined by DataBC.

**Comment by cmhodgson** [comment]
Not sure how I can estimate work that is yet to be defined?

**Comment by mraross** [comment]
Would you rather I venture a wild guess?

**Comment by cmhodgson** [comment]
I'm estimating a week of work for supporting the build and configuration management, and 2 weeks for the startup optimization which I expect to entail creating a new maximally pre-processed binary data format (possibly using protocol buffers), and code to write it and read it.

**Comment by alixcote** [comment]
Older ticket. Closing.
