### ISSUE TITLE
duplicate unit number information causes geocoder to ignore unit number and geocode to an unintended address

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#79]
The presence of "ROOM 108" in addition to the unit number "108" makes the geocoder take the first 108 as the site number, causing the wrong address to be geocoded. Removal of either 108 or ROOM 108 generates the correct geocoder address.
Input address:
108 122 HASTINGS ST E ROOM 108, VANCOUVER, BC
Geocoder address:
RM 108 -- 108 E Hastings St, Vancouver, BC

Since the geocoder recognizes both ways of representing the unit number, could it operate on the basis that 108 really is the unit number (i.e. it was not a mistake) and the other number must therefore be the site number?

Thank you

**Comment by mraross** [comment]
Very interesting. That's seems eminently doable to me. How often does this happen in the MSP address dataset?

**Comment by cmhodgson** [comment]
If we did this you can never address room 1 in unit 1 in building 1 at 1 1st st. (you don't even need that many "1"s but I think you get the idea...)
I guess if we added a minor fault to this interpretation then then if the exact match exists it would be preferred... maybe this is doable.

**Comment by mraross** [comment]
Verified in 4.1 silver on dev with the following test case:

108 122 HASTINGS ST E ROOM 108, VANCOUVER, BC

**Comment by BK01** [comment]
Validated in Geocoder 4.1 gold release
