### ISSUE TITLE
Treat occupant names found out of context as occupant-name-not-allowed faults instead of unrecognized-word faults 

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#80]
A number of addresses in the MSP address dataset include names of site occupants within an address line that is otherwise free of issues. Examples of these are:
Addresses of seniors care facilities, e.g.:
- Berwick (30 addresses)
- The Gardens (36 addresses)
- Amica (23 addresses)
- Sunrise of <City name> (15 addresses)
- Churchill House (24 addresses)

Addresses of schools and other occupant types are also occurring in small numbers.

These occupants exist in the GSR dataset, which is known to the Geocoder. Could the Geocoder validate the name found in the address against the GSR and, if found, assign only a minor penalty?

**Comment by mraross** [comment]
This is potential grist for the address salvage mill.

**Comment by cmhodgson** [comment]
This can be done but I'm not sure the amount of time it would take to do occupant lookup on every unrecognized word...

**Comment by mraross** [comment]
We could add an indexed occupant word table to speed it up. In any case, I see this as a salvage operation where time is less important than accuracy.

**Comment by mraross** [comment]
This could also be handled simply as a deep match heuristic that tacks on a frontGate on successive words starting from the first word and stops when a good match is found.

**Comment by mraross** [comment]
Verified in 4.1 silver. Handled by garbage pickup.

**Comment by mraross** [comment]
Verified in v4.1 gold in test.
