### ISSUE TITLE
Add COMP as a recognized postal address element by the Geocoder

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#83]
The MSP address reject file has 131 addresses with the text COMP \<number\> in the address line.

COMP is a valid Canada Post abbreviation for "compartment", which is used in rural roads and other cases.

The Geocoder errors are confusing: [LOCALITY.spelledWrong:2, LOCALITY.notMatched:35].

Could the COMP abbreviation be added to the Geocoder's known vocabulary, similar to PO BOX? And similarly the penalty could be reduced, same as PO BOX, which gets only a 1 point penalty?

Examples:
690 DEVINA DR COMP 8, GALIANO ISLAND, BC
807 PINEVIEW DR COMP 21, KALEDEN, BC

**Comment by mraross** [comment]
Absolutely.

**Comment by cmhodgson** [comment]
This should be easy to add to the existing pobox/RR#/etc postal element logic.

**Comment by cmhodgson** [comment]
COMP is now accepted as "POSTAL JUNK".

**Comment by BK01** [comment]
Validated in Geocoder 4.1-Gold (DLV)

Results:
690 DEVINA DR COMP 8, GALIANO ISLAND, BC
=> 
690 Devina Dr, Galiano Island, BC
[POSTAL_ADDRESS_ELEMENT.notAllowed]
[Score = 99]

807 PINEVIEW DR COMP 21, KALEDEN, BC
=>
807 Pineview Dr, Kaleden, BC
[POSTAL_ADDRESS_ELEMENT.notAllowed]
[Score = 99]
