### ISSUE TITLE
Add a too-many-minor-faults fault when too many minor faults are incurred

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#86]
Multiple 1 point faults leaving score above 89 is probably not a good match. Does it makes sense to add a too-many-minor-faults fault if more than three(?) one-point faults were incurred. I don't think we have to worry about zero-point faults.

**Comment by cmhodgson** [comment]
We will need to identify the specific cases where this is a problem and also consider cases which are correctly identified but have multiple fault in order to identify the exact situations where this new fault can help.

**Comment by mraross** [comment]
Here's a good case:

1045 317 Haro St Vancouver BC

**Comment by cmhodgson** [comment]
This has been implemented and is applied to the example address above.

**Comment by BK01** [comment]
Validated in Geocoder 4.1-Gold (DLV)

1045 317 Haro St Vancouver BC
=>
UNIT 1045 -- 317 Harbour Ave, District of North Vancouver, BC

element: "FAULTS",
fault: "tooMany",
penalty: 6
