### ISSUE TITLE
Test addresses on segments with RoadClass of Trail

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-geocoder#87]
Graeme identified a significant number of roads currently of class restricted, which should be trails, in particular in the False Creek area near granville island. These were likely driveable roads previously but are now walking/biking trails, but represent the primary access to many homes. One example address in the area is: 1301 island Park Walk, Vancouver, BC

The class of these roads should be changed in order for the router to behave properly in this area, but we want to make sure that this data change to the data doesn't adversely effect the geocoder.

**Comment by gleeming** [comment]
I don't think there will be any issues on geocoder if ITN changes the cases in False Creek to have road classes of trail.

I found an existing example in ITN on transport line ID 2586227.  That segment is named Lakeview Rd, has a road class of trail, and has an ITN address range.  More specifically, there is a nearby AddressBC parcel point at 4361 Lakeview Rd that correctly geocodes in prod onto the trail segment.  This civic number also falls within ITN's address range, providing an external measure of consistency.  So it appears that features with a road class of trail are valid candidates for address allocation.

**Comment by mraross** [comment]
Done
