### ISSUE TITLE
Assess how GeoBC address ranges might be used to supplement geocoder input data

### ISSUE THREAD

**Issue by gleeming** [bcgov/ols-geocoder#88]
Investigate how site point candidates and ranges interact in the geocoder range allocation logic.

Would ITN ranges or anchor points (like RNF) be beneficial?
Could segments with no site allocations or sparse allocations be identified and targeted for supplementing by ITN ranges?

**Comment by gleeming** [comment]
I have created a standalone FME script that generates offset anchor point records from the end range values on addressed ITN block faces, similar to the logic used for RNF.  Unlike RNF and open data addresses, it isn't part of the site candidate hybrid processing input script (site_prep.fme) because we do not need to canonicalize the street name via batch geocoding.  This saves a lot of time and memory, as the script outputs a file identical to the site loader TSV used in the block assignment and address range generator code.  The site prep workbench script that does the batch reconciliation, scoring, deduplication, etc now reads in this ITN anchor range TSV and appends it directly into the TSV it normally outputs.

There will need to be changes to the BAARG code to accommodate these new points (over 1M of them).  Ideally the application of anchor points could change from the current approach to have the enhancements such as:
1) Change the allocation process to deal allocating real sites onto block faces
2) Then apply ITN anchor points (identifiable via the INPUT_NAME field) onto block faces that have no addressing from step #1.  Probably ignore other cases and overlaps.
3) Repeat #2 but with RNF anchor points.

**Comment by gleeming** [comment]
A decision has been made for v4.1 to use ITN ranges, drop RNF inputs and not make any code changes to the BAARG.

**Comment by mraross** [comment]
Verified in v4.1 gold.
