### ISSUE TITLE
Add support for AT as an alias of AND in an intersection address

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#89]
@mraross commented on [Tue Apr 28 2020](https://github.com/bcgov/ols-router/issues/269)

This is useful for all types of intersections but particularly hwy exits such as:

     Hwy 1 at Exit 350

**Comment by mraross** [comment]
Can this be done with an abbreviation? safely?

**Comment by cmhodgson** [comment]
I don't think it can be done with an abbreviation mapping. It can be added easily though.

**Comment by mraross** [comment]
It might be useful to use the keyword "at" instead of "and" in the standard form of an exit intersection. For example:

                    Hwy 1 at Exit 305 Eastbound

In any case, allowing "at" as an alias for "and" would be helpful for both exit intersections and street intersections.
                   
2. Extend the intersection feature in the geocoder data model to support exit intersection. Minimally, this would require the following additional intersection properties:

            routeNumber - provincial route number; municipal freeways may not have a route number
            routeName - provincial route name (e.g., Trans Canada highway)
            localName - freeway name or local name of provincial highway (e.g., Ginger Goodwyn Way)
            exit - exit number of intersection of route and start point of off-ramp (e.g. 305, 104A)
            travelDirection- direction of travel at the exit (e.g., EB, WB, NB, SB)

Optionally, the following could be added if data is available:

            exitTo - destination exit leads to (e.g., Chilliwack)

This would allow intersection searches by route number, provincial route name, and local route name, exit number, and travel direction.

Here are some example exit queries:

            Hwy 1 at Exit 305
            Hwy 1 at Exit 305 to Chilliwack
            Hwy 1 at Exit to Chilliwack
            Hwy 1 at Chilliwack
            Hwy 1 at Exit 305 EB

**Comment by alixcote** [comment]
Closing until client requests.
