### ISSUE TITLE
Add support for localityType and localityTypeNot parameters

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#90]
Add support for &localityType and &localityTypeNot input parameters that allow you to filter out locality-level address matches by locality type (e.g., Resort Municipality). These parameters can take a list of comma-separated values.

**Comment by cmhodgson** [comment]
I believe these should filter all matches which have a localityType (not just locality-level matches) for consistency. Possibly matches without a localityType value (eg. BC) would still match any value of localityTypeNot.

**Comment by mraross** [comment]
As discussed, the current need is for the localityType filter to be applied to locality-level matches only.

**Comment by alixcote** [comment]
Use Case: Same name but different locality level, ie small town vs city. No current known use cases, but could come up in the future.
